### ISSUE TITLE
App Crashes after Adding a generated SDK Token from Dashboard

### ISSUE THREAD

**Issue by Hamid-Mehmood** [onfido/onfido-android-sdk#114]
#### What application i am using?

`https://github.com/onfido/onfido-android-sdk`

Sample Application in Android SDK.

#### What was the expected behaviour?

After clicking on any of verification options the app should start verification flow. 

#### What happened instead?

App Crashes.

#### Version info:

- `onfido-capture-sdk` version: 5.6.0
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 16
- Support library version (if applicable):

#### Steps to reproduce:

Replaced the `sdkToken` token with generated token from dashboard and when clicks of any of verification options the app crashes. 

#### Additional LogCat output:

1st try :

```
020-03-23 11:57:59.215 9766-9766/? W/System.err: com.onfido.android.sdk.capture.errors.OnfidoException: Unexpected result Intent. It might be a result of incorrect integration, make sure you only pass Onfido intent to handleActivityResult. It might be due to unpredictable crash or error. Please report the problem to android-sdk@onfido.com. Intent: null 
2020-03-23 11:57:59.215 9766-9766/? W/System.err:  resultCode: 0
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at com.onfido.android.sdk.capture.OnfidoImpl$handleActivityResult$corruptedResultCallback$1.invoke(Unknown Source:49)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at com.onfido.android.sdk.capture.OnfidoImpl$handleActivityResult$corruptedResultCallback$1.invoke(Unknown Source:0)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at com.onfido.android.sdk.capture.OnfidoImpl.handleActivityResult(Unknown Source:55)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at com.onfido.android.app.sample.MainActivity.onActivityResult(:64)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:8110)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4192)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-03-23 11:57:59.215 9766-9766/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

2nd try onwards:

```
  --------- beginning of crash
2020-03-23 12:03:44.619 9893-9893/com.onfido.sampleapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.onfido.sampleapp, PID: 9893
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.onfido.sampleapp/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value
        at com.onfido.api.client.t.f.a.b(:762)
        at com.onfido.api.client.t.f.a.a(:463)
        at com.onfido.api.client.t.f.b.b(:414)
        at com.onfido.api.client.t.f.b.a(:397)
        at com.onfido.api.client.t.f.a.b(:660)
        at com.onfido.api.client.t.f.a.c(:664)
        at com.onfido.api.client.token.b.b.a(:34)
        at com.onfido.api.client.token.b.b.a(:21)
        at com.onfido.api.client.token.b.a.a(:27)
        at com.onfido.api.client.h.a(:34)
        at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source:18)
        at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPI(Unknown Source:7)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:10)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:4)
        at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get(Unknown Source:0)
        at com.onfido.dagger.internal.a.get(Unknown Source:15)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:34)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:2)
        at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupPresenter(Unknown Source:12)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(Unknown Source:106)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

```

**Comment by gokhanaliccii** [comment]
@Hamid-Mehmood Can you please check sdkToken generation https://github.com/onfido/onfido-android-sdk#41-sdk-token, it seems you used `apiToken` or `mobileToken`
