### ISSUE TITLE
InflateException on WelcomeFragment

### ISSUE THREAD

**Issue by kkosobudzki** [onfido/onfido-android-sdk#117]
#### What was the expected behaviour?
Onfido flow run successfully

#### What happened instead?
Crash on Welcome screen (mostly on Android 6.0):

```
Fatal Exception: android.view.InflateException: Binary XML file line #68: Binary XML file line #68: Error inflating class ImageView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at com.onfido.android.sdk.capture.ui.WelcomeFragment.onCreateView()
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.a(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.j(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.a(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.a.f(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.b(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.a(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.b(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.l(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5857)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
```

#### Version info:

- `onfido-capture-sdk` version: 5.2.0
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 19
- Support library version (if applicable):

#### Issue severity information (number of users/crashes if applicable):
More than 200 users.

#### Other useful info:
_screenshots, videos, etc._

**Comment by gokhanaliccii** [comment]
@kkosobudzki  sorry for the inconvenience, we fixed that crash with [5.3.1](https://github.com/onfido/onfido-android-sdk/releases/tag/5.3.1) version but I'd suggest bumping to the [latest SDK version ](https://github.com/onfido/onfido-android-sdk/releases/tag/5.6.0)

**Comment by gokhanaliccii** [comment]
@kkosobudzki Have you had a chance to check the [latest SDK version](https://github.com/onfido/onfido-android-sdk/releases/tag/5.6.0)

**Comment by kkosobudzki** [comment]
It seems to be working fine with `5.6.0`, thank you! I will re-open it in case we receive similar stack trace on new version.
