### ISSUE TITLE
NullPointerException at CameraSourcePreview.setFrameCallback, onfido 5.5.0

### ISSUE THREAD

**Issue by kzaikin** [onfido/onfido-android-sdk#118]
#### What was the expected behaviour?
No crashes from Onfido

#### What happened instead?
A crash
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.setFrameCallback(com.onfido.android.sdk.capture.ui.camera.FrameCallback)' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.setFrameCallback()
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCameraPreviewAvailable()
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview$SurfaceCallback.onSurfaceTextureAvailable()
       at android.view.TextureView.getHardwareLayer(TextureView.java:392)
       at android.view.TextureView.draw(TextureView.java:330)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.draw(View.java:17332)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at android.view.View.updateDisplayListIfDirty(View.java:16251)
       at android.view.View.draw(View.java:17070)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
       at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:991)
       at android.view.View.draw(View.java:17332)
       at com.android.internal.policy.DecorView.draw(DecorView.java:977)
       at android.view.View.updateDisplayListIfDirty(View.java:16259)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
       at android.view.Choreographer.doCallbacks(Choreographer.java:709)
       at android.view.Choreographer.doFrame(Choreographer.java:644)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6259)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

#### Version info:

- `onfido-capture-sdk` version: 5.5.0
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 23
- Support library version (if applicable):
- `androidxCore`                 : "1.1.0",
- `androidxAppcompat`            : "1.0.2",

#### Steps to reproduce:
Unknown - we've got a crash from production

#### Onfido Flow initialization code:
    val steps = arrayOf(
      CaptureScreenStep(documentType.toOnfidoDocumentType(), toOnfidoCountry(nationality)),
      FaceCaptureStep(FaceCaptureVariantVideo())
    )
    val config = OnfidoConfig.builder(context!!)
      .withToken(applicantConfig.mobileSdkToken)
      .withApplicant(applicantConfig.applicantId)
      .withCustomFlow(steps)
      .build()
    val intent = onfido.createIntent(config)
    startActivityForResult(intent, REQUEST_CODE_ONFIDO)

#### Issue severity information (number of users/crashes if applicable):
Single crash so far

#### Other useful info:
Device
Brand: CUBOT
Model: CUBOT KING KONG
Orientation: Portrait
RAM free: 716.95 MB
Disk free: 2.79 GB

Operating System
Version: 7.0
Orientation: Portrait
Rooted: No

**Comment by burakeregar** [comment]
Hi @kzaikin 

Did you get more crashes since then? If so, can you please share more information? 

Thanks

**Comment by YuriDenison** [comment]
Hi @burakeregar 
Yes, we are still getting these crashes on regular basis. What additional information do you need?

- Android 9, Redmi Note 8
- Android 8, U_PRO
- Android 9, FIG-LX1

`
Fatal Exception: java.lang.RuntimeException: Unable to resume activity com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.setFrameCallback(com.onfido.android.sdk.capture.ui.camera.FrameCallback)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3866)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3898)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
`

**Comment by nuriking** [comment]
huawei p30 lite

**Comment by burakeregar** [comment]
Thanks all for the extra information. Even though we are not able to reproduce the issue on our side, we have made some fixes and improvements which we expect it to fix this issue. We are planning to release the fix with the next version.

**Comment by gokhanaliccii** [comment]
Thanks for your patience, the [7.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/7.2.0) has been released please let us know if the issue still exists on 7.2.0
