### ISSUE TITLE
java.lang.NullPointerException CameraSource.isRecording()

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#12]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.onfido.android.sdk.capture.ui.camera.face.CameraSource.isRecording()' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.isRecording(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onStop(Unknown Source)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)
       at android.app.Activity.performStop(Activity.java:7108)
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4202)
       at android.app.ActivityThread.-wrap25(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by shaubert** [comment]
samsung 66%
LENOVO 17%
HUAWEI 17%

Galaxy J3(2016) 25%
SM-G532F 23%
Galaxy S6 13%
Galaxy J2 13%
Galaxy Note5 13%

Operating Systems
7 58%
5 25%
6 17%

**Comment by sergiomarquesmoura** [comment]
Hey @shaubert . From what I understood, you're currently using our `2.3.0` version. A newer `2.4.0` version was released last week, it might be worth to upgrade and check if the issues persist or not.

**Comment by seewah** [comment]
fixed in version `3.0.0`. See [changelog](https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD#300---2018-04-05)
