### ISSUE TITLE
Denied camera permission with "do not ask again" option, Onfido crashes when re-requesting permission

### ISSUE THREAD

**Issue by alexfacciorusso** [onfido/onfido-android-sdk#126]
#### What was the expected behaviour?
Onfido Activity should return with the `CAMERA_PERMISSION_DENIED` status.

#### Version info:

- `onfido-capture-sdk` version: 5.5.0
- Android API version(s): 29

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 19

#### Steps to reproduce:
1. the user starts the Onfido flow and reaches the camera permission step
2. they deny the camera permission, onfido goes back 1 step
3. the user goes to the camera permission step again
4. the user denies the camera permission, tapping (or selecting the checkbox in some Android versions) "Do not answer again"
5. Onfido SDK crashes 

#### Onfido Flow initialization code:
```
val onfidoConfig = OnfidoConfig.builder(context)
            .withSDKToken(onfidoSdkConfig.token)
            .withCustomFlow(arrayOf(
                FlowStep.CAPTURE_DOCUMENT,
                FaceCaptureStep(FaceCaptureVariantVideo(true)),
                FlowStep.FINAL
            ))
            .build()

val intent = client.createIntent(onfidoConfig)
fragment.startActivityForResult(intent, requestCode)
```

#### Additional LogCat output:
```
10:16:26.165	AndroidRuntime	FATAL EXCEPTION: main
java.lang.IndexOutOfBoundsException: setSpan (-1 ... 2) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1330)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
	at com.onfido.android.sdk.capture.common.permissions.PermissionsManagementFragment.getAppNameSpannableStringForInstruction(Unknown Source:63)
	at com.onfido.android.sdk.capture.common.permissions.PermissionsManagementFragment.onCameraPermissionNeeded(Unknown Source:35)
	at com.onfido.android.sdk.capture.common.permissions.PermissionsManagementPresenter.checkPermissions(Unknown Source:73)
	at com.onfido.android.sdk.capture.common.permissions.PermissionsManagementFragment.onStart(Unknown Source:38)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2730)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by burakeregar** [comment]
Hi @alexfacciorusso,

Thanks for reporting the issue. Do you have localisation on your end?  More specifically, are you overriding any of the strings below? If so, you may have forgotten to include `%1$s` part which is needed on the Permission Denied screen.

`onfido_camera_access_recover_instructions_title`
`onfido_mic_access_recover_instructions_title`
`onfido_camera_mic_access_recover_instructions_title`

If that's not the case, have you had a chance to try it with the latest version of the SDK? If so, are you able to reproduce it on the latest version as well?

**Comment by alexfacciorusso** [comment]
Yes, we do have localisation on our end and we do overwrite the `onfido_camera_access_recover_instructions_title` with a string that does not have the placeholder, so I think mystery solved and this issue can be closed, but definitely to be taken as suggestion to allow in future translations without placeholders in case the project needs them!
