### ISSUE TITLE
Crashes when Hardware Acceleration is Disabled

### ISSUE THREAD

**Issue by mdesjardins** [onfido/onfido-android-sdk#137]
#### What was the expected behaviour?
No crash

#### What happened instead?
Crash

#### Version info:

- `onfido-capture-sdk` version: 4.11.1 (Yes, I know it's old, we haven't been able to update to the new API yet 😬)
- Android API version(s): 9, 10, 11
- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 23
- Support library version (if applicable): appcompat 1.2.0

#### Steps to reproduce:
Uncertain, stack traces are showing up in Crashlytics, and haven't been able to reproduce the problem yet.

#### Onfido Flow initialization code:
        val flowStepsWithOptions = arrayOf(FlowStep.WELCOME, FlowStep.CAPTURE_DOCUMENT, FlowStep.FINAL)
        val config = OnfidoConfig.builder()
                .withToken(sdk_token)
                .withApplicant(applicant_id)
                .withCustomFlow(flowStepsWithOptions)
                .build()

#### Issue severity information (number of users/crashes if applicable):
Halted rollout after 23 affected users

#### Additional LogCat output:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.face.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.face.CameraSource$PictureCallback, boolean)' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.takePicture(CameraSourcePreview.java:8)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture(CaptureActivity.java:37)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$capture(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$onPermissionsGranted$1.onClick(CaptureActivity.java:5)
       at android.view.View.performClick(View.java:7869)
       at android.view.View.performClickInternal(View.java:7838)
       at android.view.View.access$3600(View.java:886)
       at android.view.View$PerformClick.run(View.java:29362)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

#### Other useful info:
Our app was getting native crashes that are likely unrelated to Onfido on Samsung Devices running SDK 26. In an attempt to stop them, we disabled all hardware acceleration app-wide. This fixed our native crashes, but we started having crashes within Onfido immediately after - my question is whether or not Onfido requires Hardware Acceleration to function properly. I searched the closed issues, and none of the NullPointerExceptions that have been addressed in newer versions of the SDK sound like they are related to our specific problem.

Right now we are trying to decide whether we should try updating the Onfido SDK, or if it makes more sense to try enabling hardware acceleration on an Activity level on order to leave it enabled for Onfido.

Thanks!

**Comment by mdesjardins** [comment]
Hello again - I was just able to reproduce the issue with version 7.2.0 of the SDK running locally - same stack trace, so upgrading probably won't solve the problem.

**Comment by mdesjardins** [comment]
I should probably mention how I was disabling hardware acceleration - it was through the Android Manifest, in the application element:
```
<application
        android:name="com.sendwave.remit.RemitApp"
        android:icon="@mipmap/ic_wave_launcher"
        android:roundIcon="@mipmap/ic_wave_launcher_round"
        android:label="@string/app_name"
        android:theme="@style/WaveTheme"
        android:hardwareAccelerated="false"
        android:networkSecurityConfig="@xml/${networkPolicyConfig}"
        android:allowBackup="false">
    ```

**Comment by gokhanaliccii** [comment]
@mdesjardins sorry for the crash, thank you for sharing how to reproduce the crash. 

A new ticket created in our internal system to fix it, we'll share an update when the issue is fixed
