### ISSUE TITLE
Old OkHttp version

### ISSUE THREAD

**Issue by xrigau** [onfido/onfido-android-sdk#144]
#### What was the expected behaviour?

I'd expect this SDK to use a recent OkHttp version (latest stable is `4.9.0` – [OkHttp Changelog](https://square.github.io/okhttp/changelog/).

#### What happened instead?

Instead it's using an older version of OkHttp (`3.12.12`, it seems). This causes incompatibility issues as there are breaking changes between the 2 versions of OkHttp, meaning that when we attempt to use the Onfido SDK, it's crashing after taking the front picture of a document.

#### Version info:

- `onfido-capture-sdk` version: 8.0.0
- Android API version(s): All

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 27
- Support library version (if applicable): N/A

#### Steps to reproduce:

1. Take a project using OkHttp `4.9.0`
2. Add the Onfido SDK version `8.0.0`
3. Run the app
4. Start a document upload
5. Select any document type & any country, if necessary
6. Take front picture and select "My license is readable"
7. Crash occurs

#### Onfido Flow initialization code:

```kotlin
val config = OnfidoConfig.builder(this).withSdkToken("some-token").build()
val client = OnfidoFactory.create(this).client
val intent = client.createIntent(config)
startActivityForResult(intent, CODE)
```

#### Issue severity information (number of users/crashes if applicable):

The SDK crashes every time

#### Additional LogCat output:

```
com.my.package E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.my.package, PID: 29159
    java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/com.my.package-lK6mpVDPwxuQ7ycBa1prHQ==/base.apk!classes4.dex)
        at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:114)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:173)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.onfido.api.client.OnfidoFetcher$AuthTokenInterceptor.intercept(OnfidoFetcher.java:151)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

com.my.package E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.package, PID: 29159
    java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/com.my.package-lK6mpVDPwxuQ7ycBa1prHQ==/base.apk!classes4.dex)
        at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:114)
        at com.onfido.api.client.OnfidoAPI$Callback.onFailure(OnfidoAPI.java:120)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onFailure$1$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:96)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$7JZMXmGMmuA6QMd5UmiN1rIhtW0.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

#### Other useful info:

N/A

**Comment by burakeregar** [comment]
Hi @xrigau,

We were unable to use the latest version of the Okhttp due to Android 4.x support. However, we dropped Android 4.x support on our latest [release (8.0.0)](https://github.com/onfido/onfido-android-sdk/releases/tag/8.0.0). So, now we are unblocked and already have an internal ticket to update the Okhttp dependency. I will update here once it's released.

**Comment by xrigau** [comment]
@burakeregar Thanks for your quick reply!

I know these are tricky dates with the holidays coming, but do you have a rough estimate of when we can expect a new version of the SDK with a recent OkHttp version? Would you say it's in the order of weeks or months or else?

Thanks!

**Comment by burakeregar** [comment]
Unfortunately, I don't have an exact date for this but I can say that there is no plan for releasing this before the new year.

**Comment by blundell** [comment]
FWIW it gives you the 3.x to 4.x migration steps here: https://square.github.io/okhttp/upgrading_to_okhttp_4/

**Comment by gokhanaliccii** [comment]
We've migrated to Okhttp 4.9 on [9.0.0](https://github.com/onfido/onfido-android-sdk/releases/tag/9.0.0) version. 

Thanks for your patience

**Comment by xrigau** [comment]
Excellent! Just a heads-up that OkHttp 5.x is coming out soon https://square.github.io/okhttp/changelog/#version-500-alpha2
