### ISSUE TITLE
Stuck in a loop while taking selfies

### ISSUE THREAD

**Issue by Ishmael-ZT** [onfido/onfido-android-sdk#147]
#### What was the expected behaviour?

Once a selfie has been captured, the user should see a confirmation screen where they can confirm that the selfie is clear and in focus, after confirmation the user leaves the flow.

#### What happened instead?

When the user captures and confirms a photo, they are redirected back to the selfie intro. If they attempt to take a photo again the same thing happens and a loop is formed.

#### Version info:

- `onfido-capture-sdk` version: 7.2.0
- Android API version(s):

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Steps to reproduce:

Crashes every-time, putting the customer in a loop

#### Other useful info:

There have been no reports in production as yet

https://user-images.githubusercontent.com/72451080/105362356-79059b80-5c03-11eb-8f88-f3f41d9132dd.mp4

#### Onfido Flow initialization code:

      
```

val flowSteps = arrayOf(
    FlowStep.CAPTURE_FACE,
)

val onfidoConfig = OnfidoConfig.builder(requireActivity())
    .withSDKToken(
        /** some token **/,
        viewModel.getTokenExpirationHandler(BuildConfig.APPLICATION_ID)
    )
    .withCustomFlow(flowSteps)
    .build()

onfidoClient.startActivityForResult(
    this,
    ONFIDO_CAPTURE_REQUEST_CODE,
    onfidoConfig
)

```

####  Additional LogCat output:

```

Fatal Exception: java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/j0/j/h; or its super classes (declaration of 'okhttp3.j0.j.h' appears in /data/app/co.bitx.android.wallet-9nihQg5Y2EHetyTdTUINGg==/base.apk!classes3.dex)
at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:114)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:173)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
at com.onfido.api.client.OnfidoFetcher$AuthTokenInterceptor.intercept(OnfidoFetcher.java:151)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764) 

```

**Comment by andra-radu** [comment]
Hi @Ishmael-ZT,

Could you please share with us your initialisation flow and Additional LogCat output so that we can further investigate? Yo can do this by emailing api@onfido.com and reference https://github.com/onfido/onfido-android-sdk/issues/147. Thank you.

**Comment by Ishmael-ZT** [comment]
I have a stack trace, I am starting to suspect that this could be a dependancy clash as we recently bumped up Okhttp

Fatal Exception: java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/j0/j/h; or its super classes (declaration of 'okhttp3.j0.j.h' appears in /data/app/co.bitx.android.wallet-9nihQg5Y2EHetyTdTUINGg==/base.apk!classes3.dex)
       at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:114)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:173)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.onfido.api.client.OnfidoFetcher$AuthTokenInterceptor.intercept(OnfidoFetcher.java:151)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by Ishmael-ZT** [comment]
I also tried upgrading to SDK version 8.0.0 the issue persists.

**Comment by Ishmael-ZT** [comment]
I have reverted to Okhttp 3, as Onfido sdk versiojn 8.0.0 works with this version. Hoping we will be able to migrate to OkHttp 4 soon.
