### ISSUE TITLE
Proguard integration

### ISSUE THREAD

**Issue by apperside** [onfido/onfido-android-sdk#15]
Hi, I am trying to run an obfuscated version of my app, and it seem there some some obfuscation realted issue.
As suggested by you [here](https://github.com/onfido/onfido-android-sdk/issues/13), I added this to my proguard file

-keep public class com.onfido.android.sdk.** { public protected *; }

but it seem it's not enough: i get this exception

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
                                                     at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.a(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onDocumentUploaded(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.a$1.a(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.a$1.onSuccess(Unknown Source)
                                                     at com.onfido.api.client.OnfidoAPI$Callback.onResponse(OnfidoAPI.java:124)
                                                     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

I can't find anything related to proguard in your docs, are there specific rules that I need to add?

Thanks

**Comment by sergiomarquesmoura** [comment]
Hello! Thanks for reporting.
Could you try to also keep classes with the package `com.onfido.api.client` ?
Shipping the rules embedded with the SDK is indeed something in our near-future plans

**Comment by apperside** [comment]
Thanks, that did the trick! Using this configuration it seem works

```
-keep class com.onfido.android.sdk.** {
  public protected private *;
}
-keep class com.onfido.api.client.** {
  public protected private *;
}
```

**Comment by sergiomarquesmoura** [comment]
I agree @apperside , at the time we ship the rules with the SDK, more granular ones will be provided. In the meantime, for a more granular rule here, you can try to keep just `com.onfido.api.client.data.DocType`, which is an enum class.
