### ISSUE TITLE
SDk is crashing on Lollipop version  

### ISSUE THREAD

**Issue by sumitkhandebharad** [onfido/onfido-android-sdk#153]
#### What was the expected behaviour?
 To allow user to use the app without crash
#### What happened instead?
Application is Crashed on opening in Android Lollipop os
#### Version info: 

- `onfido-capture-sdk` version: 5.1.0
- Android API version(s): 21/22

- `compileSdkVersion`:30
- `targetSdkVersion`:30
- `minSdkVersion`:21
- Support library version (if applicable): 

#### Issue severity information (number of users/crashes if applicable):
Highest

#### Additional LogCat output:
java.lang.NullPointerException: Attempt to get length of null array
    at java.lang.String.<init>(String.java:206)
    at com.onfido.zxing.a.a.void d()(AESCrypt.java:8)
    at com.onfido.zxing.pdf417.a.a.b.x(Version.java:1)
    at com.onfido.zxing.pdf417.a.a.b.G(Version.java:3)
    at com.winvesta.android.MyApplication.onCreate(MyApplication.java:10)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

#### Other useful info:
_screenshots, videos, etc._

**Comment by gokhanaliccii** [comment]
Hi @sumitkhandebharad,
Sorry for the inconvenience, it seems the problem occurs on the zxing library side which we no longer use with [7.2.0](https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD#720---20200706) version. 

I'd suggest starting to use the [latest](https://github.com/onfido/onfido-android-sdk/releases/tag/9.2.0) SDK version

**Comment by sumitkhandebharad** [comment]
@gokhanaliccii 
Do we need to any upgrade on the backend side ?
our backend is on V2 API version of Onfido 
If needed please do suggest/Guide us to the migration documentation.
