### ISSUE TITLE
TokenExpirationHandler serializable crash

### ISSUE THREAD

**Issue by brunoescalona** [onfido/onfido-android-sdk#160]
#### What was the expected behaviour?

I want to implement the token expiration handler and as is described in the documentation I have created an instance of the class with my logic in it to handle the token.

> If you want to use tokenExpirationHandler you should pass concrete class instance, you should not pass an anonymous or activity class instance.

```
class ExpirationHandler : TokenExpirationHandler {

        override fun refreshToken(injectNewToken: (String?) -> Unit) {
            TODO("Your network request logic to retrieve SDK token goes here")
            injectNewToken("NEW_SDK_TOKEN") // if you pass `null` sdk exit with token expired error
        }
    }

val config = OnfidoConfig.builder(context)
    .withSDKToken("YOUR_SDK_TOKEN_HERE", tokenExpirationHandler = ExpirationHandler()) // ExpirationHandler is optional
```

#### What happened instead?

The problem is that if we want to include the network logic I need to inject my service to fetch the new token.

If I inject something in that `ExpirationHandler` class I am getting the followin error:

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.onfido.android.sdk.capture.OnfidoConfig)
        at android.os.Parcel.writeSerializable(Parcel.java:2113)
        at android.os.Parcel.writeValue(Parcel.java:1883)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1303)
        at android.os.Parcel.writeBundle(Parcel.java:1044)
        at android.content.Intent.writeToParcel(Intent.java:10855)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3668)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
        at android.app.Activity.startActivityForResult(Activity.java:5320)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
        at android.app.Activity.startActivityForResult(Activity.java:5278)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
        at com.onfido.android.sdk.capture.OnfidoImpl.startActivityForResult(Unknown Source:17)
```

So I am not sure if the instance that I am injecting should also be `Serializable` 

How can I could solve that issue?

#### Version info:

- `onfido-capture-sdk` version: 9.2.0

**Comment by gokhanaliccii** [comment]
Can you please ensure your ExpirationHandler classes' properties also Serializable?

**Comment by brunoescalona** [comment]
Hey @gokhanaliccii thanks for your answer but I already tried, the problem is that we are using dagger for dependecy injection and because of that the service is depending in other services and properties that also needs to be serializable. So is not possible to do it. Is there any other way to do it?

**Comment by gokhanaliccii** [comment]
Unfortunately, it seems not possible apart from making other properties serializable

**Comment by Dsanchez1992** [comment]
You could put @Transient annotation to the properties that you could inject to the ExpirationHandler class
Example: 
```
class ExpirationHandler(@Transient val propertie: SomeClassType) : TokenExpirationHandler {
}
```
