### ISSUE TITLE
Crash: JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by leolangen** [onfido/onfido-android-sdk#161]
#### What was the expected behaviour?
Launch a document capture flow using the SDK token

#### What happened instead?
App crashes

#### Version info:

- `onfido-capture-sdk` version: 9.3.0
- Android API version(s): 7, 9

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 23
- Support library version (if applicable): 28.0.0

#### Steps to reproduce:
Launch SDK using SDK token

#### Onfido Flow initialization code:
OnfidoConfig
                        .builder(this@DocumentActivity)
                        .withCustomFlow(
                                arrayOf(FlowStep.CAPTURE_DOCUMENT)
                        )
                        .withSDKToken(
                            onfidoKey,
                            ExpirationHandler())
                        .build()

#### Issue severity information (number of users/crashes if applicable):
10 crashes 2 users on new release (released on 2 May, 19:00 PM UTC)

#### Additional LogCat output:

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{.../com.onfido.android.sdk.capture.ui.OnfidoActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{.../com.onfido.android.sdk.capture.ui.OnfidoActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2844)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6364)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by com.google.gson.JsonSyntaxException
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Caused by com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at com.onfido.api.client.token.sdk.model.SDKTokenPayload.parseSDKTokenPayload(SDKTokenPayload.java:31)
       at com.onfido.api.client.token.sdk.url.IDVUrlCreator.createApiUrl(IDVUrlCreator.java:15)
       at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:36)
       at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34)
       at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient()
       at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPI()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get()
       at com.onfido.dagger.internal.a.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideSDKConfigRepositoryFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideSDKConfigRepositoryFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoPresenterFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoPresenterFactory.get()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity_MembersInjector.injectMembers()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity_MembersInjector.injectMembers()
       at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2844)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6364)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by java.lang.IllegalStateException
Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Caused by java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
       at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at com.onfido.api.client.token.sdk.model.SDKTokenPayload.parseSDKTokenPayload(SDKTokenPayload.java:31)
       at com.onfido.api.client.token.sdk.url.IDVUrlCreator.createApiUrl(IDVUrlCreator.java:15)
       at com.onfido.api.client.token.sdk.SDKToken.buildUrl(SDKToken.java:36)
       at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:34)
       at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient()
       at com.onfido.android.sdk.capture.common.di.SdkModule.provideOnfidoAPI()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoAPIFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoApiServiceFactory.get()
       at com.onfido.dagger.internal.a.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideSDKConfigRepositoryFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideSDKConfigRepositoryFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoPresenterFactory.get()
       at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoPresenterFactory.get()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity_MembersInjector.injectMembers()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity_MembersInjector.injectMembers()
       at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith()
       at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2844)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6364)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

#### Other useful info:
_screenshots, videos, etc._

**Comment by leolangen** [comment]
Similar error to this issue: https://github.com/onfido/onfido-android-sdk/issues/101
Could not find information on how to resolve the crash

**Comment by leolangen** [comment]
Could this crash happen if we are passing the old Mobile token to the `withSDKToken` function?

**Comment by leolangen** [comment]
If this is a crash due to sending the incorrect token value, I would still keep this issue open as the SDK should not crash under this scenario, surely it should handle the invalid SDK token and fail graciously

**Comment by gokhanaliccii** [comment]
> Could this crash happen if we are passing the old Mobile token to the withSDKToken function?

Yes that's the common case and it could also occur when you pass an invalid SDK token

We have a ticket in our internal backlog to handle invalid SDK token, thank you for your patience
