### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException y + height must be <= bitmap.height()

### ISSUE THREAD

**Issue by vmaximov** [onfido/onfido-android-sdk#164]
#### What was the expected behaviour?
SDK should not crash

#### What happened instead?
SDK Crashed

#### Version info:

- `onfido-capture-sdk` version: 8.1.0
- Android API version(s): 7.1.2

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 23
- Support library version (if applicable):

#### Steps to reproduce:

Crash was reported in Firebase

#### Additional LogCat output:
```
Fatal Exception: java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
       at android.graphics.Bitmap.createBitmap(Bitmap.java:737)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:701)
       at com.onfido.android.sdk.capture.utils.ImageUtils.cropImage(ImageUtils.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.uploadDocumentForValidation(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.uploadImageForValidation(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.confirmed(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.ConfirmationStepButtons$setDocumentCaptureActions$$inlined$apply$lambda$1.onClick(ConfirmationStepButtons.java)
       at android.view.View.performClick(View.java:5637)
       at android.view.View$PerformClick.run(View.java:22429)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6145)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

#### Other useful info:
_screenshots, videos, etc._

**Comment by gokhanaliccii** [comment]
@vmaximov sorry for the inconvenience, I've added a ticket in our internal backlog to track this issue once we have an update, we'll keep you posted.

In the meantime, could you please help us on these questions;
- do you know how many users were affected by this crash
- does this crash occur on a specific phone?
- does this crash occur on the latest version (10.0.0)
