### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: surfaceTexture must not be null

### ISSUE THREAD

**Issue by JuzTosS** [onfido/onfido-android-sdk#178]
#### What was the expected behaviour?
No crash
#### What happened instead?
Crash
#### Version info:

- `onfido-capture-sdk` version: 9.1.0
- Android API version(s):
Device
Brand:LENOVO
Model:Lenovo Tab P11
Orientation: Portrait
RAM free: 1.13 GB
Disk free: 89.11 GB
Operating system
Version:Android 11
Orientation: Portrait
Rooted:No

- `compileSdkVersion`:
- `targetSdkVersion`:
- `minSdkVersion`:
- Support library version (if applicable):

#### Steps to reproduce:
Unknown
#### Additional LogCat output:
Fatal Exception: java.lang.IllegalArgumentException: surfaceTexture must not be null
       at android.view.Surface.<init>(Surface.java:255)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.createCameraSource(CameraSourcePreview.java:58)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startWithException(CameraSourcePreview.java:4)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.start(CameraSourcePreview.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.start(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCameraPreviewAvailable(CaptureActivity.java:46)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.onCameraPreviewAvailable(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview$SurfaceCallback.onSurfaceTextureAvailable(CameraSourcePreview.java:9)
       at android.view.TextureView.getTextureLayer(TextureView.java:402)
       at android.view.TextureView.draw(TextureView.java:351)
       at android.view.View.updateDisplayListIfDirty(View.java:21251)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.draw(View.java:22382)
       at android.view.View.updateDisplayListIfDirty(View.java:21251)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21242)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21242)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21242)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21242)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21242)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21242)
       at android.view.View.draw(View.java:22110)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.draw(View.java:22382)
       at com.android.internal.policy.DecorView.draw(DecorView.java:831)
       at android.view.View.updateDisplayListIfDirty(View.java:21251)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4116)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3843)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3114)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1958)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8246)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
       at android.view.Choreographer.doCallbacks(Choreographer.java:878)
       at android.view.Choreographer.doFrame(Choreographer.java:811)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7791)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
#### Other useful info:
_screenshots, videos, etc._

**Comment by gurpreet-onfido** [comment]
Hello @JuzTosS 

We have fixed this issue back in the release 10.3.0 of our SDK. Could you please upgrade the Onfido Android SDK to the latest release 11.3.0 and let us know if the issue still persists.

Kind regards
Gurpreet Singh

**Comment by JuzTosS** [comment]
Thank you!
