### ISSUE TITLE
CountrySelectionFragment - NullPointerException

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#18]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.widget.RecyclerView.exitLoadingState()' on a null object reference
       at com.onfido.android.sdk.capture.ui.country_selection.CountrySelectionFragment$f.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by shaubert** [comment]
This is a top issue in our crashlytics report, affecting around 250 users in last 7 days.

**Comment by sergiomarquesmoura** [comment]
Hello @shaubert !
This issue was already tackled by us and a release fixing it should be out this week

**Comment by sergiomarquesmoura** [comment]
Hello @shaubert !
This issue was fixed on the latest`3.0.0`
