### ISSUE TITLE
Exception when Relaunching from Background

### ISSUE THREAD

**Issue by KennethNickles** [onfido/onfido-android-sdk#183]
#### What was the expected behaviour?
When backgrounding and immediately relaunching the app we noticed the OnfidoActivity is destroyed. When our activity is restarted and foregrounded it receives a cancel result from the OnfidoActivity. When we pass that cancel result onto the OnFidoClient we expect to get an userExited event.

#### What happened instead?
We see the exception thrown below. We also noticed that if enough time is allowed to pass between backgrounding and relaunching the app we instead get a userExited event from instead of an exception. This leads us to believe it is a race condition in the result handling code in the sdk.

Another tidbit: I noticed our usage of singleInstance for our main Activity could be the culprit in killing the OnFidoActivity.

#### Version info:

- `onfido-capture-sdk` version: 11.4.1
- Android API version(s): 

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24
- Support library version (if applicable):  1.6.0

#### Steps to reproduce:
Start OnFidoActivity for a result using client
Background App
Relaunch App from Launch, etc.

#### Onfido Flow initialization code:

```
  override fun showOnfido(
      sdkToken: String,
      flowSteps: Array<FlowStep>,
      eventListener: UserEventHandler
  ) {
    val onfidoConfig = OnfidoConfig.builder(context)
        .withCustomFlow(flowSteps)
        .withSDKToken(sdkToken)
        .build()

    onfidoHelper.showOnfido(onfidoConfig, eventListener)
  }

...

class OnfidoHelperImpl constructor(private val activity: Activity): OnfidoHelper {
  private val onfidoClient by lazy { OnfidoFactory.create(activity).client }

  override fun showOnfido(onfidoConfig: OnfidoConfig, eventListener: UserEventHandler) {
    Onfido.userEventHandler = eventListener
    onfidoClient.startActivityForResult(activity,
      ApplicationConstants.REQUEST_CODE_ONFIDO, onfidoConfig)
  }

  override fun handleActivityResult(resultCode: Int, data: Intent?, listener: OnfidoResultListener) {
    onfidoClient.handleActivityResult(resultCode, data, listener)
  }

  /**
   * Cleans up reference to UserEventListener so we're not
   * leaking it when activity closes
   */
  override fun onDetachFromWindow() {
    Onfido.userEventHandler = null
  }
}
```

#### Issue severity information (number of users/crashes if applicable):
679 crashes and 512 users ~ 30days

#### Additional LogCat output:
```
FATAL EXCEPTION: main
Process: com.affirm.central.stage_sandbox.debug, PID: 11325
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
  ComposedException 1 :
	com.onfido.android.sdk.capture.errors.OnfidoException: Unexpected result Intent. It might be a result of incorrect integration, make sure you only pass Onfido intent to handleActivityResult. It might be due to unpredictable crash or error. Please report the problem to android-sdk@onfido.com. Intent: null resultCode: 0
		at com.onfido.android.sdk.capture.OnfidoImpl$handleActivityResult$corruptedResultCallback$1.invoke(Unknown Source:48)
		at com.onfido.android.sdk.capture.OnfidoImpl$handleActivityResult$corruptedResultCallback$1.invoke(Unknown Source:0)
		at com.onfido.android.sdk.capture.OnfidoImpl.handleActivityResult(Unknown Source:55)
		at com.affirm.auth.implementation.onfido.OnfidoHelperImpl.handleActivityResult(OnfidoHelperImpl.kt:23)
		at com.affirm.auth.implementation.identity.ShowOnfidoPresenter.onOnfidoActivityResult(ShowOnfidoPresenter.kt:272)
		at com.affirm.auth.implementation.identity.ShowOnfidoPresenter.access$onOnfidoActivityResult(ShowOnfidoPresenter.kt:51)
		at com.affirm.auth.implementation.identity.ShowOnfidoPresenter$onAttach$3.invoke(ShowOnfidoPresenter.kt:132)
		at com.affirm.auth.implementation.identity.ShowOnfidoPresenter$onAttach$3.invoke(ShowOnfidoPresenter.kt:131)
		at io.reactivex.rxkotlin.SubscribersKt$sam$io_reactivex_functions_Consumer$0.accept(Unknown Source:2)
		at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7870)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by KennethNickles** [comment]
I'll walk through the repo again today and get back to you. I don't remember seeing any other crashes besides onfido's.

**Comment by kushal-onfido** [comment]
Hey @KennethNickles Just following up on this to see if you found anything else about this issue?
Thanks!

**Comment by KennethNickles** [comment]
@kushal-onfido The activity was definitely backgrounded. The result intent being received comes from a foregrounding after Onfido was backgrounded and subsequently killed while in the background.

**Comment by KennethNickles** [comment]
Closing, we wrote some logic to prevent the null result.
