### ISSUE TITLE
Fatal Exception when passing in an invalid cert pins

### ISSUE THREAD

**Issue by charlieneedham** [onfido/onfido-android-sdk#186]
#### What was the expected behaviour?

The SDK returning gracefully with an error

#### What happened instead?

The SDK crashes with a Fatal Exception

#### Version info:

- `onfido-capture-sdk` version: 11.3.0
- Android API version(s):  

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 23
- Support library version (if applicable):

#### Steps to reproduce:

Build the onfidoConfig.Builder with an invalid cert pin passed to withCertificatePinning(). Start the Onfido activityForResult and it throws a fatal exception

#### Onfido Flow initialization code:
onfidoClient = OnfidoFactory.create(this).getClient();
List<FlowStep> flowSteps = new ArrayList<>();
flowSteps.add(DocumentCaptureStepBuilder.forDrivingLicence().withCountry(CountryCode.CA).build());
flowSteps.add(FaceCaptureStepBuilder.forVideo().build());

OnfidoConfig.Builder onfidoConfigBuilder = OnfidoConfig.builder(this).withSDKToken(onfidoToken);
onfidoConfigBuilder.withCustomFlow(flowSteps.toArray(new FlowStep[0]));
onfidoConfigBuilder.withEnterpriseFeatures(new EnterpriseFeatures(true));
// Using a dummy cert pin
String[] certPins = {"BLAH"};
onfidoConfigBuilder.withCertificatePinning(certPins);
onfidoConfig = onfidoConfigBuilder.build();
onfidoClient.startActivityForResult(this, ONFIDO_RESULT_ID, onfidoConfig);

#### Issue severity information (number of users/crashes if applicable):

It always crashes

#### Additional LogCat output:

2022-05-03 15:14:21.728 5262-5262/com.securekey.ivssampleapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.securekey.ivssampleapp, PID: 5262
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.securekey.ivssampleapp/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.IllegalArgumentException: pins must start with 'sha256/' or 'sha1/': BLAH
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3898)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.IllegalArgumentException: pins must start with 'sha256/' or 'sha1/': BLAH
        at okhttp3.CertificatePinner$Pin.<init>(CertificatePinner.kt:272)
        at okhttp3.CertificatePinner$Builder.add(CertificatePinner.kt:338)
        at com.onfido.api.client.OnfidoFetcher.configureCertificatePinning(OnfidoFetcher.java:106)
        at com.onfido.api.client.OnfidoFetcher.<init>(OnfidoFetcher.java:80)
        at com.onfido.api.client.OnfidoFetcher.create(OnfidoFetcher.java:131)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule.provideOnfidoFetcherAPIV3$onfido_capture_sdk_core_release(Unknown Source:33)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoFetcherAPIV3$onfido_capture_sdk_core_releaseFactory.provideOnfidoFetcherAPIV3$onfido_capture_sdk_core_release(Unknown Source:2)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoFetcherAPIV3$onfido_capture_sdk_core_releaseFactory.get(Unknown Source:24)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoFetcherAPIV3$onfido_capture_sdk_core_releaseFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoAPIV3$onfido_capture_sdk_core_releaseFactory.get(Unknown Source:10)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoAPIV3$onfido_capture_sdk_core_releaseFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoApiService$onfido_capture_sdk_core_releaseFactory.get(Unknown Source:2)
        at com.onfido.android.sdk.capture.common.di.network.NetworkModule_ProvideOnfidoApiService$onfido_capture_sdk_core_releaseFactory.get(Unknown Source:0)
        at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(Unknown Source:2)
        at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(Unknown Source:0)
        at j.a.get(Unknown Source:13)
        at com.onfido.android.sdk.capture.ui.OnfidoPresenter_Factory.get(Unknown Source:38)
        at com.onfido.android.sdk.capture.ui.OnfidoPresenter_PresenterAssistedFactory_Impl.create(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity$presenter$2.invoke(Unknown Source:12)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity$presenter$2.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.getPresenter(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith(Unknown Source:60)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(Unknown Source:54)
        at android.app.Activity.performCreate(Activity.java:8121)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
2022-05-03 15:14:21.728 5262-5262/com.securekey.ivssampleapp E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3871)
        	... 11 more
2022-05-03 15:14:21.790 1495-2029/? E/InputDispatcher: channel '8fae6a1 com.securekey.ivssampleapp/com.securekey.ivs.sdk.impl.IvsStartActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2022-05-03 15:14:21.798 1495-2029/? E/InputDispatcher: channel '1f26d4b com.securekey.ivssampleapp/com.securekey.ivssampleapp.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

#### Other useful info:
_screenshots, videos, etc._

**Comment by ramprasad-parajuli** [comment]
Thank you @charlieneedham.  We are not going to prioritize the issue for now as it is a minor improvement since a wrong certificate should not be provided, and there is no recovery step.
Please do let us know if you think it is required to be prioritized and we will assess the issue accordingly.

**Comment by charlieneedham** [comment]
It might not be a priority but I don't think the SDK should ever crash.
