### ISSUE TITLE
Fatal Exception: getReadabilityConfirmationLabel() on a null object reference

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#187]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

926 crash events affecting 609 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.onfido.android.sdk.capture.ui.model.DocumentTypeUIModel.getReadabilityConfirmationLabel()' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setConfirmationButtons(CaptureActivity.java:22)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onUploadValidationError(CapturePresenter.java:96)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCaptureValidationError(CaptureActivity.java:11)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onUploadError(CaptureActivity.java:82)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.parseUploadError(CaptureUploadService.java:36)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.access$parseUploadError(CaptureUploadService.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService$uploadSelfie$livePhotoSuccessListener$1.onError(CaptureUploadService.java:2)
       at com.onfido.android.sdk.capture.network.OnfidoApiService$OnfidoApiListener.onError(OnfidoApiService.java:45)
       at com.onfido.api.client.OnfidoAPI$Callback.onResponse(OnfidoAPI.java:165)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:89)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$hVGjmafRi6VitDIrPNdoFizVAdk(DefaultCallAdapterFactory.java)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$0$daf5173ad73a9dc0e8131143f299c222e2ca4cddd7cb10b2d0a6e331a0602ae1$0.run(DefaultCallAdapterFactory.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
