### ISSUE TITLE
Fatal Exception: IllegalArgumentException surfaceTexture must not be null

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#188]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5 (not sure for this one)
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

731 crash events affecting 568 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.IllegalArgumentException: surfaceTexture must not be null
       at android.view.Surface.<init>(Surface.java:287)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.createCameraSource(CameraSourcePreview.java:72)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.startWithException(CameraSourcePreview.java:4)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.start(CameraSourcePreview.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.start(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startCameraForVideo(CaptureActivity.java:22)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.updateCameraRequirements(CaptureActivity.java:17)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.updateCameraState(CapturePresenter.java:55)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.closeConfirmationStep(CaptureActivity.java:35)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.discarded(CapturePresenter.java:5)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onDocumentUploaded(CapturePresenter.java:30)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onDocumentUploaded(CaptureActivity.java:4)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService$uploadDocument$documentSuccessListener$1.onSuccess(CaptureUploadService.java:6)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService$uploadDocument$documentSuccessListener$1.onSuccess(CaptureUploadService.java:2)
       at com.onfido.android.sdk.capture.network.OnfidoApiService$OnfidoApiListener.onSuccess(OnfidoApiService.java:2)
       at com.onfido.api.client.OnfidoAPI$Callback.onResponse(OnfidoAPI.java:167)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:89)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$hVGjmafRi6VitDIrPNdoFizVAdk(DefaultCallAdapterFactory.java)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$0$daf5173ad73a9dc0e8131143f299c222e2ca4cddd7cb10b2d0a6e331a0602ae1$0.run(DefaultCallAdapterFactory.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
