### ISSUE TITLE
Fatal Exception: CameraSource.takePicture on a null object reference

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#189]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

402 crash events affecting 328 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.view.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.view.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.view.CameraSource$PictureCallback, boolean)' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.takePicture(CameraSourcePreview.java:8)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture(CaptureActivity.java:33)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupCaptureButton$lambda-13(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.$r8$lambda$2ZKQN5Ws-kxsfpzA-QdCkgf4bOo(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$$InternalSyntheticLambda$0$b6b4fb1cca4e0252d3e7f188439f987f9d6ceae2efac86419009757a79db6f21$0.onClick(CaptureActivity.java:2)
       at android.view.View.performClick(View.java:6600)
       at android.view.View.performClickInternal(View.java:6577)
       at android.view.View.access$3100(View.java:781)
       at android.view.View$PerformClick.run(View.java:25917)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
