### ISSUE TITLE
Fatal Exception: IllegalArgumentException: Invalid picture size: 0x0

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#190]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

231 crash events affecting 179 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid picture size: 0x0
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource$Builder.isCameraSizeValid(CameraSource.java:39)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource$Builder.setRequestedPictureSize(CameraSource.java)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourceFactory.createCameraSource(CameraSourceFactory.java:50)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.createCameraSource(CameraSourcePreview.java:92)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.startWithException(CameraSourcePreview.java:4)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.start(CameraSourcePreview.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.start(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startCameraForVideo(CaptureActivity.java:10)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.updateCameraRequirements(CaptureActivity.java:17)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.updateCameraState(CapturePresenter.java:55)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onCaptureScreenResumedAfterCameraInitialized$onfido_capture_sdk_core_release(CapturePresenter.java:61)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCameraPreviewAvailable(CaptureActivity.java:20)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.onCameraPreviewAvailable(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview$SurfaceCallback.onSurfaceTextureAvailable(CameraSourcePreview.java:9)
       at android.view.TextureView.getTextureLayer(TextureView.java:402)
       at android.view.TextureView.draw(TextureView.java:351)
       at android.view.View.updateDisplayListIfDirty(View.java:21230)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.draw(View.java:22357)
       at android.view.View.updateDisplayListIfDirty(View.java:21230)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21221)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21221)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21221)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21221)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21221)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.updateDisplayListIfDirty(View.java:21221)
       at android.view.View.draw(View.java:22085)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.draw(View.java:22357)
       at com.android.internal.policy.DecorView.draw(DecorView.java:806)
       at android.view.View.updateDisplayListIfDirty(View.java:21230)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8186)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
       at android.view.Choreographer.doCallbacks(Choreographer.java:878)
       at android.view.Choreographer.doFrame(Choreographer.java:811)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7725)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by melihberberolu** [comment]
Any update ?

**Comment by RicardAparicio** [comment]
Same here
