### ISSUE TITLE
Fatal Exception: IllegalArgumentException: surfaceTexture must not be null

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#191]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5 (not sure for this one)
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

198 crash events affecting 92 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.IllegalArgumentException: surfaceTexture must not be null
       at android.view.Surface.<init>(Surface.java:186)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.createCameraSource(CameraSourcePreview.java)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.startWithException(CameraSourcePreview.java)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.start(CameraSourcePreview.java)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.start(CameraWrapper.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startCameraForVideo(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.updateCameraRequirements(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.updateCameraState(CapturePresenter.java)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onUploadFailure(CapturePresenter.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onUploadError(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService$uploadDocument$documentSuccessListener$1.onUploadError(CaptureUploadService.java)
       at com.onfido.android.sdk.capture.network.OnfidoApiService$OnfidoApiListener.onFailure(OnfidoApiService.java)
       at com.onfido.api.client.OnfidoAPI$Callback.onFailure(OnfidoAPI.java:155)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onFailure$1(DefaultCallAdapterFactory.java:96)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$G9BY9eQQk64nBfFjfIpx-YzJzUo(DefaultCallAdapterFactory.java)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$0$863fee28ad386a31df1b34a5fdab70e8ff0b54307838f0066a86e93c2ba4282e$0.run(DefaultCallAdapterFactory.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
