### ISSUE TITLE
Fatal Exception: RuntimeException: Unknown camera ID

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#193]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

23 crash events affecting 8 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.RuntimeException: Unknown camera ID
       at android.hardware.Camera._getCameraInfo(Camera.java)
       at android.hardware.Camera.getCameraInfo(Camera.java:448)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getIdForRequestedCamera(CameraSource.java:13)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.createCamera(CameraSource.java:10)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.start(CameraSource.java:15)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.startWithException(CameraSourcePreview.java:23)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.start(CameraSourcePreview.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.start(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startCameraForVideo(CaptureActivity.java:22)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.updateCameraRequirements(CaptureActivity.java:17)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.updateCameraState(CapturePresenter.java:55)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCameraPreviewAvailable(CaptureActivity.java:49)
       at com.onfido.android.sdk.capture.ui.camera.CameraWrapper.onCameraPreviewAvailable(CameraWrapper.java:2)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview$SurfaceCallback.onSurfaceTextureAvailable(CameraSourcePreview.java:9)
       at android.view.TextureView.getTextureLayer(TextureView.java:415)
       at android.view.TextureView.draw(TextureView.java:360)
       at android.view.View.updateDisplayListIfDirty(View.java:21389)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.draw(View.java:22538)
       at android.view.View.updateDisplayListIfDirty(View.java:21389)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.updateDisplayListIfDirty(View.java:21380)
       at android.view.View.draw(View.java:22254)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
       at android.view.View.draw(View.java:22538)
       at com.android.internal.policy.DecorView.draw(DecorView.java:848)
       at android.view.View.updateDisplayListIfDirty(View.java:21389)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4448)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4175)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3422)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2206)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8763)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
       at android.view.Choreographer.doFrame(Choreographer.java:1049)
       at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1275)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
