### ISSUE TITLE
Fatal Exception: RuntimeException: cancelAutoFocus failed

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#196]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

13 crash events affecting 11 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.RuntimeException: cancelAutoFocus failed
       at android.hardware.Camera.native_cancelAutoFocus(Camera.java)
       at android.hardware.Camera.cancelAutoFocus(Camera.java:1445)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.cancelAutoFocus(CameraSource.java:7)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.revertAutoFocusMode(CameraSource.java:51)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.lambda$autoFocusOnce$4(CameraSource.java:7)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.$r8$lambda$bwR94_xk5O7tWcFZgMGY4mAjceU(CameraSource.java)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource$$InternalSyntheticLambda$0$7ed2f7d83f8e08a88e18c9f4cdd9c2ee885c781a483c0c1def75e290165c386d$1.onAutoFocus(CameraSource.java:6)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.autoFocus(CameraSource.java:36)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.autoFocusOnce(CameraSource.java:36)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.autoFocusOnce(CameraSource.java:1)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview$1.onClick(CameraSourcePreview.java:21)
       at android.view.View.performClick(View.java:6600)
       at android.view.View.performClickInternal(View.java:6577)
       at android.view.View.access$3100(View.java:781)
       at android.view.View$PerformClick.run(View.java:25917)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
