### ISSUE TITLE
Fatal Exception: Drawable.getIntrinsicWidth() on a null object reference

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#197]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5
- Android API version(s):

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

11 crash events affecting 11 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
       at com.onfido.android.sdk.capture.ui.ZoomImageView.transformCoordTouchToBitmap(ZoomImageView.java:11)
       at com.onfido.android.sdk.capture.ui.ZoomImageView.access$2100(ZoomImageView.java)
       at com.onfido.android.sdk.capture.ui.ZoomImageView$DoubleTapZoom.<init>(ZoomImageView.java:34)
       at com.onfido.android.sdk.capture.ui.ZoomImageView$PrivateOnTouchListener.onTouch(ZoomImageView.java:225)
       at android.view.View.dispatchTouchEvent(View.java:15195)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:915)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:873)
       at android.view.View.dispatchPointerEvent(View.java:15458)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by kushal-onfido** [comment]
Hello @artur-melnyk 

This has been fixed in the latest Android SDK version [13.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/13.2.0). You are requested to upgrade the SDK to the latest version and contact Onfido support if you still see this crash happening. 

Thank you!
