### ISSUE TITLE
Fatal Exception: IllegalArgumentException: y + height must be <= bitmap.height()

### ISSUE THREAD

**Issue by artur-melnyk** [onfido/onfido-android-sdk#199]
#### Version info:

- `onfido-capture-sdk` version: 10.3.5

- Android API version(s): 30
- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 24

#### Issue severity information (number of users/crashes if applicable):

7 crash events affecting 1 users in 90 days

#### Additional LogCat output:

```
Fatal Exception: java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
       at com.onfido.android.sdk.capture.utils.ImageUtils.cropImage$onfido_capture_sdk_core_release(ImageUtils.java:72)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.uploadDocument(CaptureActivity.java:12)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.uploadImage(CaptureActivity.java:28)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onPostCaptureValidationsFinished(CapturePresenter.java:42)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.applyPostCaptureValidations$lambda-34(CapturePresenter.java)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.$r8$lambda$5z1JS1zhBIOLq4VpYvzgLV7DSBs(CapturePresenter.java)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter$$InternalSyntheticLambda$0$f841181c17a999b4a6c3a459b7d049a112e654c8d97a4d1e678475e29b045c45$0.accept(CapturePresenter.java:6)
       at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
       at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by gurpreet-onfido** [comment]
Hello @artur-melnyk 

We are sorry for the inconvenience this might have caused. We've added a ticket in our internal backlog to track this issue once we have an update, we'll keep you posted.

In the meantime, could you please help us on these questions:

1.  Does this crash occur on a specific phone?
2. Does this crash occur on the latest version (12.0.0)?

Looking forward to your response.

Kind regards,
Gurpreet Singh

**Comment by artur-melnyk** [comment]
> 

Hi, this crash occur on Samsung SMG991B.
Unfortunately can't check on version 12.0.0 yet
