### ISSUE TITLE
NPEs at ui.camera.CaptureActivity.setConfirmationButtons(CaptureActivity.java:22)

### ISSUE THREAD

**Issue by Ishmael-ZT** [onfido/onfido-android-sdk#203]
#### What was the expected behaviour?
After capturing a clear self portrait photo the user should be able to successfully upload the photo

#### What happened instead?
Crash occurs when uploading self portrait photos 

#### Version info:

- `onfido-capture-sdk` version: 12.1.0
- Android API version(s): 26, 28, 29, 30

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Steps to reproduce:

This seems to occur when uploading self portrait photos

#### Onfido Flow initialization code: 

```
val flowStep = FaceCaptureStepBuilder
    .forPhoto()
    .withIntro(false)
    .build()

val flowSteps: Array<FlowStep> = arrayOf(flowStep)

val onfidoConfig = OnfidoConfig.builder(requireActivity())
    .withSDKToken(token)
    .withCustomFlow(flowSteps)
    .build()
    
onfidoClient.startActivityForResult(
    this,
    ONFIDO_CAPTURE_REQUEST_CODE,
    onfidoConfig
)
```

#### Issue severity information (number of users/crashes if applicable):

This issue has 278 crash events affecting 168 users in the last 7 days between 7th and 13th of May.

#### Additional LogCat output:

```
Fatal Exception: java.lang.NullPointerException
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setConfirmationButtons(CaptureActivity.java:22)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onUploadValidationError$onfido_capture_sdk_core_release(CapturePresenter.java:106)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCaptureValidationError(CaptureActivity.java:11)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onUploadError(CaptureActivity.java:86)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.parseUploadError(CaptureUploadService.java:36)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.access$parseUploadError(CaptureUploadService.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService$uploadSelfie$livePhotoSuccessListener$1.onError(CaptureUploadService.java:12)
       at com.onfido.android.sdk.capture.network.OnfidoApiService$OnfidoApiListener.onError(OnfidoApiService.java:50)
       at com.onfido.api.client.OnfidoAPI$Callback.onResponse(OnfidoAPI.java:156)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:89)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$hVGjmafRi6VitDIrPNdoFizVAdk(DefaultCallAdapterFactory.java)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$0$daf5173ad73a9dc0e8131143f299c222e2ca4cddd7cb10b2d0a6e331a0602ae1$0.run(DefaultCallAdapterFactory.java:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by Ishmael-ZT** [comment]
```
Fatal Exception: java.lang.NullPointerException
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setConfirmationButtons(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onUploadValidationError$onfido_capture_sdk_core_release(CapturePresenter.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCaptureValidationError(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onUploadError(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.parseUploadError(CaptureUploadService.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.access$parseUploadError(CaptureUploadService.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService$uploadSelfie$livePhotoSuccessListener$1.onError(CaptureUploadService.java)
       at com.onfido.android.sdk.capture.network.OnfidoApiService$OnfidoApiListener.onError(OnfidoApiService.java)
       at com.onfido.api.client.OnfidoAPI$Callback.onResponse(OnfidoAPI.java:156)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:89)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$hVGjmafRi6VitDIrPNdoFizVAdk(DefaultCallAdapterFactory.java)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$0$daf5173ad73a9dc0e8131143f299c222e2ca4cddd7cb10b2d0a6e331a0602ae1$0.run(DefaultCallAdapterFactory.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6179)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by Ishmael-ZT** [comment]
> @Ishmael-ZT thank you for flagging the issue. We were able to reproduce the issue. We are currently trying to fix the issue from our end. I will provide an update once the fix is released.

I am relieved to hear this

**Comment by ramprasad-parajuli** [comment]
@Ishmael-ZT, thank you for your patience.
I am glad to let you know that the issue has been fixed from our end and the fix has been released with the latest SDK release, i.e., [12.3.0](https://github.com/onfido/onfido-android-sdk/releases/tag/12.3.0).
Could you please upgrade the Android SDK to avoid the issue going forward?

**Comment by Ishmael-ZT** [comment]
Thank you so much!
