### ISSUE TITLE
Nasty crash if sdk token is invalid

### ISSUE THREAD

**Issue by mzealey** [onfido/onfido-android-sdk#22]
#### What was the expected behaviour?

I was accidentally using a JWT rather than the SDK token as required. The app crashed in a difficult-to-diagnose way. Perhaps you should throw some nicer exception?

#### What happened instead?

App crashed like

```
04-27 15:22:24.453 21596 21596 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.NullPointerException: baseUrl == null
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-27 15:22:24.453 21596 21596 E AndroidRuntime: Caused by: java.lang.NullPointerException: baseUrl == null
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at retrofit2.Utils.checkNotNull(Utils.java:285)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:493)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.api.client.OnfidoFetcher.<init>(OnfidoFetcher.java:59)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.api.client.OnfidoFetcher.create(OnfidoFetcher.java:77)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:19)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.api.client.OnfidoAPIFactory.create(OnfidoAPIFactory.java:48)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.android.sdk.capture.utils.OnfidoApiUtil.createOnfidoApiClient(Unknown Source)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.android.sdk.capture.ui.OnfidoActivity.b(Unknown Source)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(Unknown Source)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6684)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
04-27 15:22:24.453 21596 21596 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
```

**Comment by sergiomarquesmoura** [comment]
Hi @mzealey !
Thanks for reporting this. Indeed, we should provide a clearer explanation of what happened, and we will make sure we add it in an upcoming release
