### ISSUE TITLE
ArrayIndexOutOfBoundsException in Exif.java line 92 

### ISSUE THREAD

**Issue by Ishmael-ZT** [onfido/onfido-android-sdk#222]
#### What was the expected behaviour?
Customer must capture and submit a document

#### What happened instead?
Sdk appears to crash when a customer attempts to capture the front of a document specifically on a Nokia C1 or C2 mobile device

#### Version info:

- `onfido-capture-sdk` version: 13.2.0
- Android API version(s):

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Issue severity information (number of users/crashes if applicable):

This issue has 195 crash events affecting 60 users

#### Additional LogCat output:

Fatal Exception: mdi.sdk.j89: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
       at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:65)
       at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6846)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at android.media.ExifInterface.guessDataFormat(ExifInterface.java:3670)
       at android.media.ExifInterface.setAttribute(ExifInterface.java:1547)
       at com.onfido.android.sdk.capture.ui.camera.Exif.copy(Exif.java:92)
       at com.onfido.android.sdk.capture.utils.ImageUtils.cropImage$onfido_capture_sdk_core_release(ImageUtils.java:148)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.uploadDocument(CaptureActivity.java:22)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.uploadImage(CaptureActivity.java:38)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onPostCaptureValidationsFinished(CapturePresenter.java:34)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.applyPostCaptureValidations$lambda-36(CapturePresenter.java:15)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.$r8$lambda$Upakdy4SOE8NjYVZvqpM-WTN6Zo(CapturePresenter.java)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter$$InternalSyntheticLambda$0$e19da0d580c40e2f1bd46984bf0a26a5b8b3921005860ee6de863f7135c40303$0.accept(CapturePresenter.java:6)
       at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
       at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6846)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

#### Other useful info:
_screenshots, videos, etc._

**Comment by gurpreet-onfido** [comment]
Hello @Ishmael-ZT 

Greetings for the day!

We have fixed the EXIF related issue in our Android SDK version 14.0.0. You can refer to the release notes here: https://github.com/onfido/onfido-android-sdk/releases/tag/14.0.0. Could you please upgrade the SDK at your end and let us know if the issue still persists.

Kind regards
Gurpreet Singh
