### ISSUE TITLE
A fresh NullPointerException crash

### ISSUE THREAD

**Issue by alexmonese** [onfido/onfido-android-sdk#224]
#### Description
We have a few users affected by this issue. We have recently updated SDK to 14.0.0.
As I can see from the logs, it happens both in `CaptureActivity` and `OnfidoActivity`.

#### Possible solution
Add a null check before the `stopVideo` call

#### Stacktrace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.view.CameraSource.stopVideo()' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.stopRecording(SourceFile:2)
       at com.onfido.android.sdk.capture.internal.camera.Camera1Api$takeVideo$recorder$1.cancel(SourceFile:6)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onFaceOutTimeout(SourceFile:11)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.observeFaceOut$lambda-43(SourceFile:15)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.$r8$lambda$UolgxwUcv6D25uES5yBwXMXsR0g(SourceFile)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter$$InternalSyntheticLambda$0$b3cc9649fa5c2b61ea33f9c7b80ad496292099c70490f8fec391bb1434ec27c2$0.run(CapturePresenter.java:2)
       at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:89)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
#### Version info: 

- `onfido-capture-sdk` version: 14.0.0
- Android API version(s): 10, 11, 12, 13

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 21

#### Issue severity information (number of users/crashes if applicable):
At the moment 8 users have been affected, 10 crash events

**Comment by alexmonese** [comment]
Any updates on this? At the moment, we have 104 users affected and 164 events in total.
