### ISSUE TITLE
LivenessConfirmationFragment.submitResult IllegalStateException crash

### ISSUE THREAD

**Issue by alexmonese** [onfido/onfido-android-sdk#228]
#### Description
The issue is happening when `OnfidoActivity` is on the screen.

#### Stacktrace
```
Fatal Exception: java.lang.IllegalStateException: Fragment LivenessConfirmationFragment{1035e50} (6103cf2c-6e5a-421e-b848-2f212dd205f4) not associated with a fragment manager.
       at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1107)
       at com.onfido.android.sdk.capture.ui.camera.liveness.LivenessConfirmationFragment.submitResult(SourceFile)
       at com.onfido.android.sdk.capture.ui.camera.liveness.LivenessConfirmationFragment.deleteVideoAndExit(SourceFile:11)
       at com.onfido.android.sdk.capture.ui.camera.liveness.LivenessConfirmationFragment.access$deleteVideoAndExit(SourceFile)
       at com.onfido.android.sdk.capture.ui.camera.liveness.LivenessConfirmationFragment$onMediaPlayerError$1.invoke(SourceFile:10)
       at com.onfido.android.sdk.capture.ui.camera.liveness.LivenessConfirmationFragment$onMediaPlayerError$1.invoke(SourceFile:2)
       at com.onfido.android.sdk.capture.utils.AlertDialogUtilKt.showErrorDialog$lambda-3(SourceFile:10)
       at com.onfido.android.sdk.capture.utils.AlertDialogUtilKt.$r8$lambda$6IhvFslik80S47gFcJUJb-EnpP0(SourceFile)
       at com.onfido.android.sdk.capture.utils.AlertDialogUtilKt$$InternalSyntheticLambda$0$f6f9b97188a476088b969e0d523e820a13a890338e049a383cad63f91a2d6676$0.onClick(AlertDialogUtilKt.java:2)
       at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8068)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```
#### Version info:

- `onfido-capture-sdk` version: 14.0.0
- Android API version(s): Android 7, 9, 11, 12

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 21

#### Issue severity information (number of users/crashes if applicable):
11 events, 10 users

**Comment by gurpreet-onfido** [comment]
Hello @alexmonese 

Thank you for bringing this up. We have shared this crash log with the concerned team and we will update you as more updates are available with us. 

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @alexmonese 

Thank you for your time and cooperation, we appreciate it.  Since there are no concrete steps to reproduce, hence we tried to get steps from the logs:

- Record Video/Liveness -> Finish recording → Move to the Liveness Confirmation screen
- Click preview/play button
- Just recorded video can’t be displayed for some reason 
- Error pop up is shown
- Close pop up
- App should crash

We are not able to replicate it. We tried those devices (BrowserStack) with hardcoded broken file path:

- Samsung Galaxy S22 Ultra
- Samsung Galaxy S20+
- Samsung Galaxy S10

and  actual devices:

- Pixel 4 (Android 13)
- OnePlus 8T (Android 13)

Could you please let us know if you are still getting this issue on the recent SDK version.

Looking forward to your response.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @alexmonese Since there is no response from your side, we are closing this thread. Please feel free to reach out to us with the additional information we have asked above and we will take it from there.

Kind regards
Gurpreet Singh
