### ISSUE TITLE
CaptureActivity.dismissUploadingDialog line 15: IllegalArgumentException

### ISSUE THREAD

**Issue by rygelouv** [onfido/onfido-android-sdk#230]
#### Description
Seems like a crash happening when a dialog is being dismissed but the CaptureActivity is finished?

#### Version info:
- `onfido-capture-sdk` version: 15.2.0
- Android API version(s): Android 9 - 13

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 24
- Support library version (if applicable):

#### Steps to reproduce:
Unkown

#### Issue severity information (number of users/crashes if applicable):
This issue has 17 crash events affecting 14 users in 7 days
#### Additional LogCat output:
```
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@6a1f7fb[CaptureActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:604)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:508)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:146)
       at android.app.Dialog.dismissDialog(Dialog.java:676)
       at android.app.Dialog.dismiss(Dialog.java:658)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.dismissUploadingDialog(SourceFile:15)
       at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.onLoadingDialog$onfido_capture_sdk_core_release(SourceFile:51)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setLoading(SourceFile:4)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.showErrorMessage(SourceFile:1)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onGeneralUploadError(SourceFile:20)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onUploadError(SourceFile:138)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.uploadDocumentVideo$lambda-1(SourceFile:49)
       at com.onfido.android.sdk.capture.ui.camera.CaptureUploadService.$r8$lambda$V2viI1IC0u8uI7XBbgTsxYMUVX0(SourceFile)
       at com.onfido.android.sdk.capture.component.active.video.capture.presentation.intro.AVCIntroFragment$$InternalSyntheticLambda$1$372b363644d3653ca6896179d12b33bceafa85ecf6f64632e0e1b44742db3f03$0.accept$bridge(AVCIntroFragment.java:12)
       at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
#### Other useful info:
From Cashlytics: _This is a crash caused by your app dismissing a dialog attached to an Activity which is finishing or finished. This can happen in a number of ways -- for example, if an AsyncTask is running while a ProgressDialog is showing, and the user rotates the device, causing the Activity to be recreated._

**Comment by gurpreet-onfido** [comment]
Hello @rygelouv 

Greetings for the day!

Could you please let us know: 

a) If you are able to reproduce the issue consistently on your side?
b) What is the % of users affected by this crash?
c) Is it a device specific issue or it is reproducible on multiple devices?

Looking forward to your response.

Kind regards
Gurpreet Singh

**Comment by rygelouv** [comment]
Hi @gurpreet-onfido 
Thanks for responding
- I was not able to reproduce the issue myself. 
- For the last 30 days this our Crashlytics reports: 1193 crash events affecting 797 users
- It is not device specific. We can see many different devices affected by this.

**Comment by rygelouv** [comment]
Hello @gurpreet-onfido 

Just for confirmation, is [16.3.0](https://github.com/onfido/onfido-android-sdk/releases/tag/16.3.0) the version that fixes this issue?
