### ISSUE TITLE
`onError` callback is invoked instead of `userExited` when pressing "back" during loading

### ISSUE THREAD

**Issue by denis-colliot** [onfido/onfido-android-sdk#233]
#### What was the expected behaviour?

When opening the Onfido flow and quickly pressing "back" (see attached video), the following `result` provided to `handleActivityResult` should eventually invoke `userExited` instead of `onError`:
```kotlin
result = ActivityResult{resultCode=RESULT_CANCELED, data=null}
```

#### What happened instead?

When opening the Onfido flow and quickly pressing "back" (see attached video), the following `result` provided to `handleActivityResult` actually invokes `onError` (and not the expected `userExited`):
```kotlin
result = ActivityResult{resultCode=RESULT_CANCELED, data=null}
```

#### Version info:

- `onfido-capture-sdk` version: `15.4.1`
- Android API version(s): API 29 (Android 10)
- `compileSdkVersion`: `32`
- `targetSdkVersion`: `31`
- `minSdkVersion`: `24`
- Support library version (if applicable): -

#### Steps to reproduce:
1. Open the Onfido flow using `Onfido.createIntent` with any basic configuration (see below)
2. **Immediately** press "back" while Onfido screen is displaying the progress loader
3. Expect the `userExited` callback to be invoked but the `onError` callback is invoked 🐛 

#### Onfido Flow initialization code:

```kotlin
import androidx.activity.result.contract.ActivityResultContracts.StartActivityForResult
import androidx.appcompat.app.AppCompatActivity
import com.onfido.android.sdk.capture.ExitCode
import com.onfido.android.sdk.capture.Onfido
import com.onfido.android.sdk.capture.OnfidoConfig
import com.onfido.android.sdk.capture.OnfidoFactory
import com.onfido.android.sdk.capture.errors.OnfidoException
import com.onfido.android.sdk.capture.upload.Captures

class MyActivityOpeningOnfido : AppCompatActivity() {

    private val openOnfidoActivity = registerForActivityResult(StartActivityForResult()) { result ->
        onfidoClient.handleActivityResult(result.resultCode, result.data, object : Onfido.OnfidoResultListener {
            override fun onError(exception: OnfidoException) {
                viewModel.onDocumentCaptureError(exception)
            }

            override fun userCompleted(captures: Captures) {
                viewModel.onDocumentCaptureSuccess(captures)
            }

            override fun userExited(exitCode: ExitCode) {
                viewModel.onDocumentCaptureExit(exitCode)
            }
        })
    }

    // ...

    private fun openOndifoFlow() {
        val onfidoConfig = OnfidoConfig.builder(this)
                    .withSDKToken("<SDK_TOKEN>")
                    .withCustomFlow(arrayOf(DocumentCaptureStepBuilder.forPassport().build()))
                    .withAllowedDocumentTypes(listOf(DocumentType.PASSPORT))
                    .build()

        val onfidoClient: Onfido = OnfidoFactory.create(this).client
        val onfidoIntent = onfidoClient.createIntent(onfidoConfig)
        openOnfidoActivity.launch(onfidoIntent)
    }
}
```

#### Issue severity information (number of users/crashes if applicable):

Minor _but_ easily/always reproductible

#### Additional LogCat output:
> ℹ️ `com.comuto.squirrel` is our app package
```
com.onfido.android.sdk.capture.errors.OnfidoException: Unexpected result Intent. It might be a result of incorrect integration, make sure you only pass Onfido intent to handleActivityResult. It might be due to unpredictable crash or error. Please report the problem to android-sdk@onfido.com. Intent: null
 resultCode: 0
   at com.onfido.android.sdk.capture.OnfidoImpl$handleActivityResult$corruptedResultCallback$1.invoke(Unknown Source:47)
   at com.onfido.android.sdk.capture.OnfidoImpl$handleActivityResult$corruptedResultCallback$1.invoke(Unknown Source:0)
   at com.onfido.android.sdk.capture.OnfidoImpl.handleActivityResult(Unknown Source:55)
   at com.comuto.squirrel.android.identitycheck.presentation.ui.DocumentCaptureActivity.openOnfidoActivity$lambda$0(DocumentCaptureActivity.kt:52)
   at com.comuto.squirrel.android.identitycheck.presentation.ui.DocumentCaptureActivity.$r8$lambda$JNc1KxjGRXDJwxU8-SG4ZZu1Uy0(Unknown Source:0)
   at com.comuto.squirrel.android.identitycheck.presentation.ui.DocumentCaptureActivity$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
   at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
   at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
   at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:777)
   at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
   at android.app.Activity.dispatchActivityResult(Activity.java:8300)
   at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
   at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
   at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loop(Looper.java:237)
   at android.app.ActivityThread.main(ActivityThread.java:8167)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

##### ✅ When "back" is _not_ pressed when opening the Onfido flow:

https://user-images.githubusercontent.com/7382968/217503417-35ce41c0-45a1-40f9-aa75-635a98d638fe.mp4

##### 💥 When "back" is pressed when opening the Onfido flow:

> _ℹ️ The orange screen is displayed when `onError` callback in invoked_

https://user-images.githubusercontent.com/7382968/217503547-df87504c-0f69-45a0-8e1a-c075b30c577c.mp4

**Comment by gurpreet-onfido** [comment]
Hello @denis-colliot 

Greetings for the day!

We are looking into the issue that you have reported and we will get back to you on this as soon as possible.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @denis-colliot,

Greetings for the day!

We are able to reproduce this issue and developed a fix. I will drop a line here once the fix is released. 

Please stay tuned!

Kind regards
Gurpreet Singh
