### ISSUE TITLE
Fatal crash on Onfido launch when updating to version 16.3+

### ISSUE THREAD

**Issue by rygelouv** [onfido/onfido-android-sdk#243]
#### What was the expected behaviour?
Hello Onfido team.

You suggested on the issue I posted here https://github.com/onfido/onfido-android-sdk/issues/230 that it was solved in version `16.3.0` but actually, when updating to this version or version `16.30.1` it crashes our app. Video down below.

#### What happened instead?
```
Caused by: java.lang.reflect.InvocationTargetException

FATAL EXCEPTION: main
Process: com.mychime.waveremit.app.staging, PID: 11903
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mychime.waveremit.app.staging/com.onfido.android.sdk.capture.ui.OnfidoActivity}: android.view.InflateException: Binary XML file line #37 in com.mychime.waveremit.app.staging:layout/onfido_activity_onfido: Binary XML file line #13 in com.mychime.waveremit.app.staging:layout/onfido_progress_layout: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
#### Version info:

- `onfido-capture-sdk` version: 16.3.0
- Android API version(s): Android 9 - 13

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 24
- Support library version (if applicable):

#### Steps to reproduce:
Launching Onfido from our app ends in a crash. See video in section "other useful info" down below

#### Onfido Flow initialization code:
```kotlin
// Our factory uses business logic to determine which steps to include or not
val flowSteps = onfidoStepsFactory.createFlowSteps(onfidoData.steps, documentFlow) 
val config = OnfidoConfig.builder(context)
            .withSDKToken(onfidoData.token)
            .withCustomFlow(flowSteps)
```
#### Issue severity information (number of users/crashes if applicable):
This version is not in production yet. The issue was identified during developement.
#### Additional LogCat output:
```
Caused by: android.view.InflateException: Binary XML file line #37 in com.mychime.waveremit.app.staging:layout/onfido_activity_onfido: Binary XML file line #13 in com.mychime.waveremit.app.staging:layout/onfido_progress_layout: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Caused by: android.view.InflateException: Binary XML file line #13 in com.mychime.waveremit.app.staging:layout/onfido_progress_layout: Error inflating class com.google.android.material.progressindicator.CircularProgressIndicator
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(Unknown Source:5)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0403ed a=11}
	at android.content.res.TypedArray.getColor(TypedArray.java:529)
	at com.google.android.material.progressindicator.BaseProgressIndicatorSpec.loadIndicatorColors(BaseProgressIndicatorSpec.java:133)
	at com.google.android.material.progressindicator.BaseProgressIndicatorSpec.<init>(BaseProgressIndicatorSpec.java:107)
	at com.google.android.material.progressindicator.CircularProgressIndicatorSpec.<init>(CircularProgressIndicatorSpec.java:76)
	at com.google.android.material.progressindicator.CircularProgressIndicatorSpec.<init>(CircularProgressIndicatorSpec.java:68)
	at com.google.android.material.progressindicator.CircularProgressIndicatorSpec.<init>(CircularProgressIndicatorSpec.java:63)
	at com.google.android.material.progressindicator.CircularProgressIndicator.createSpec(CircularProgressIndicator.java:82)
	at com.google.android.material.progressindicator.CircularProgressIndicator.createSpec(CircularProgressIndicator.java:53)
	at com.google.android.material.progressindicator.BaseProgressIndicator.<init>(BaseProgressIndicator.java:143)
	at com.google.android.material.progressindicator.CircularProgressIndicator.<init>(CircularProgressIndicator.java:73)
	at com.google.android.material.progressindicator.CircularProgressIndicator.<init>(CircularProgressIndicator.java:68)
```
#### Other useful info:
https://user-images.githubusercontent.com/7549316/234576294-49c1ec89-fff3-44ed-8a42-a4c5aa427f95.mov

**Comment by jacques-sendwave** [comment]
Hello,

Just to let you all know that the crash was indeed related to overriding the `OnfidoActivityTheme`, after changing the UI customization following [this](https://developers.onfido.com/guide/sdk-customization#android) documentation, we were able to update the SDK to 1.6.3 without a problem.

Thanks for the help, we can close this issue now.
