### ISSUE TITLE
NPE on Flowconfig

### ISSUE THREAD

**Issue by sudansh** [onfido/onfido-android-sdk#252]
#### Version info:
- `onfido-capture-sdk` version: 16.3.2
- Android API version(s):  Android 12

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 25
- Support library version (if applicable):

#### Steps to reproduce:
Opening Onfido SDK
#### Additional LogCat output:
Caused by java.lang.NullPointerException: null cannot be cast to non-null type com.onfido.android.sdk.FlowConfig
       at com.onfido.android.sdk.capture.core.CoreActivity.onCreate(:20)
       at android.app.Activity.performCreate(Activity.java:8051)
       at android.app.Activity.performCreate(Activity.java:8031)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7838)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

#### Other useful info:
_screenshots, videos, etc._

**Comment by sudansh** [comment]
```
val onfidoSteps = arrayOf(FaceCaptureStepBuilder.forVideo().build())

   val config = OnfidoConfig.builder(context).withSDKToken("token", null).withCustomFlow(onfidoSteps).build()
   
   val onfidoHandler = OnfidoFactory.create(context).client
   
  onfidoHandler?.let {
            onfidoLauncher.launch(it.createIntent(config))
 }
```

**Comment by sudansh** [comment]
Using Compose
```
val onfidoLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.StartActivityForResult()
    ) {
      onfidoHandler?.handleActivityResult(
      ....
      )
}
```
And not calling `CoreActivity` explicitly
