### ISSUE TITLE
ANR exception after gradle update and minifyEnabled

### ISSUE THREAD

**Issue by nikolasamardzija** [onfido/onfido-android-sdk#262]
#### What was the expected behaviour?
To start onfido process

#### What happened instead?
ANR of onfido process
#### Version info:

- `onfido-capture-sdk` version: 19.0.0. same thing on 18.0.0.
- Android API version(s): 30, 31, 32, 33

- `compileSdkVersion`: 33
- `targetSdkVersion`: 31
- `minSdkVersion`: 26
- Support library version (if applicable):

#### Steps to reproduce:
Update gradle to version 8.0.2
Inside app gradle set
minifyEnabled true
shrinkResources true

#### Onfido Flow initialization code:
   val defaultStepsWithWelcomeScreen = arrayOf(
            DocumentCaptureStepBuilder.forDrivingLicence().build(),
            FaceCaptureStepBuilder.forVideo().withIntro(true).build(), // Face Capture Step
            FlowStep.FINAL // Final Screen Step, Optional
        )

        val config = OnfidoConfig.builder(requireContext())
            .withCustomFlow(defaultStepsWithWelcomeScreen)
            .withSDKToken(onfidoSdkToken.token)
            .withLocale(Locale.getDefault())
            .build()

        onfido.startActivityForResult(this, ONFIDO_REQUEST_CODE, config)

#### Issue severity information (number of users/crashes if applicable):
This issue has 285 ANR events affecting 190 users
#### Additional LogCat output:
:onfido_process (unknown):tid=16001 systid=16001 
#00 pc 0x89630 libc.so (syscall + 32) (BuildId: 1bcad8bca80d38bceb9089f70d394e33)
#01 pc 0x47a430 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140) (BuildId: a49c773ef6221a996ecea990e9753caa)
#02 pc 0x6fa7d4 libart.so (art::ThreadList::WaitForOtherNonDaemonThreadsToExit(bool) + 336) (BuildId: a49c773ef6221a996ecea990e9753caa)
#03 pc 0x32a494 libart.so (art::JII::DestroyJavaVM(_JavaVM*) + 32) (BuildId: a49c773ef6221a996ecea990e9753caa)
#04 pc 0xce520 libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool) + 1032) (BuildId: 085d4918095a60dab67deca42d990704)
#05 pc 0x2570 app_process64 (main + 1304) (BuildId: df8ee709f77c2e3b9fca33b5a3ced970)
#06 pc 0x854ec libc.so (__libc_init + 100) (BuildId: 1bcad8bca80d38bceb9089f70d394e33)

#### Other useful info:
Maybe related: https://github.com/onfido/onfido-android-sdk/issues/255
<img width="1238" alt="image" src="https://github.com/onfido/onfido-android-sdk/assets/23246626/111860fd-5f42-4ef5-98ec-6904b9119a26">

**Comment by nikolasamardzija** [comment]
Hi Musa, thanks for taking a look at this, can you tell me where to find the applicant ID?

**Comment by nikolasamardzija** [comment]
I don't log that, can you give me an example of how I can find that, is it in my codebase? I only see statistics on crashylytics

**Comment by nikolasamardzija** [comment]
Got it, since I'm getting these errors through Firebase crashlytics so I don't have an applicant id for them. But today a few of our customers reported a white screen so I have applicant ID for some of them:
7087A659-0AAC-4A49-9E6F-590D177FE5CF
FF59E417-3F4F-4843-92C2-347D88742D99
A909A0FA-F5C7-4E6B-B406-11A768F69836

btw, is it secure to share this information in the GitHub issue, we can move to email until we resolve this?

**Comment by nikolasamardzija** [comment]
Dear Musa, 
Sorry for the wait, I couldn't test it quicker. 

I'm still getting exceptions even though I updated onfido to version 19.2.0, I'm attaching stack trace from my logcat:
`FATAL EXCEPTION: main
    Process: com.myapp:onfido_process, PID: 4717
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.IllegalArgumentException: Unable to create call adapter for class io.reactivex.rxjava3.core.Single
        for method OnfidoService.getSdkConfiguration
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
    	at android.app.ActivityThread.-wrap11(Unknown Source:0)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
    	at android.os.Handler.dispatchMessage(Handler.java:105)
    	at android.os.Looper.loop(Looper.java:164)
    	at android.app.ActivityThread.main(ActivityThread.java:6541)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    Caused by: java.lang.IllegalArgumentException: Unable to create call adapter for class io.reactivex.rxjava3.core.Single
        for method OnfidoService.getSdkConfiguration
    	at retrofit2.Utils.methodError(Utils.java:54)
    	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:116)
    	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67)
    	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
    	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
    	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
    	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
    	at com.onfido.api.client.$Proxy2.getSdkConfiguration(Unknown Source)
    	at com.onfido.api.client.SdkConfigurationAPI.getConfiguration(SdkConfigurationAPI.java:20)
    	at com.onfido.api.client.OnfidoAPIImpl.getSDKConfig(OnfidoAPIImpl.java:214)
    	at com.onfido.android.sdk.capture.network.OnfidoApiService.getSDKConfig$onfido_capture_sdk_core_release(SourceFile:0)
    	at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository.<init>(SourceFile:0)
    	at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.newInstance(SourceFile:0)
    	at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(SourceFile:0)
    	at com.onfido.android.sdk.capture.internal.config.SDKConfigRepository_Factory.get(SourceFile:0)
    	at com.onfido.dagger.internal.DoubleCheck.get(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoPresenterInitializer_Factory.get(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoPresenterInitializer_Factory.get(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoPresenter_Factory.get(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoPresenter_PresenterAssistedFactory_Impl.create(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoActivity$presenter$2.invoke(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoActivity$presenter$2.invoke(SourceFile:0)
    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    	at com.onfido.android.sdk.capture.ui.OnfidoActivity.getPresenter(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith(SourceFile:0)
    	at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(SourceFile:0)
    	at android.app.Activity.performCreate(Activity.java:6975)
    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
    	... 9 more
    Caused by: java.lang.IllegalStateException: Single return type must be parameterized as Single<Foo> or Single<? extends Foo>
    	at retrofit2.adapter.rxjava3.RxJava3CallAdapterFactory.get(RxJava3CallAdapterFactory.java:123)
    	at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:253)
    	at retrofit2.Retrofit.callAdapter(Retrofit.java:237)
    	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:114)
    	... 36 more`

**Comment by TheMedo** [comment]
I am also experiencing the same issue on version `19.2.0`.

Document scanning works well on debug versions, but crashes (same stack trace as above) on release build with minify enabled.

Adding `-keep class io.reactivex.rxjava3.core.Single` to your proguard rules file seems to fix the issue.

Note: Did not test the full flow, there might be other crashes down the line.

**Comment by nikolasamardzija** [comment]
@TheMedo I've actually had to add a few more `-keep class` statements in order to build the app but it didn't solve the problem
