### ISSUE TITLE
OnfidoException The exception could not be delivered to the consumer because it has already canceled/disposed the flow

### ISSUE THREAD

**Issue by niqo01** [onfido/onfido-android-sdk#276]
#### What was the expected behaviour?

Onfido flow starts successfully

#### What happened instead?

When the app is non debuggable and minified, Onfido error callback is triggered with the following exception:
```
Non-fatal Exception: com.onfido.android.sdk.capture.errors.OnfidoException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.ExceptionInInitializerError
       at com.onfido.android.sdk.capture.ui.BaseActivity.setupCrashHandler$lambda-2(:68)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:434)
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:388)
       at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:647)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

#### Version info:

- `onfido-capture-sdk` version: 19.2.1
- Android API version(s): Android 13

- `compileSdkVersion`: 34
- `targetSdkVersion`: 33
- `minSdkVersion`: 21

#### Onfido Flow initialization code:

```
onfido = OnfidoFactory.create(csApp).getClient()
OnfidoConfig onfidoConfig = OnfidoConfig.builder(getContext())
            .withSDKToken(sdkToken)
            .withCustomFlow(onFidoSteps)
            .withAnalyticsEventListener(onfidoAnalyticsEvent -> {
              switch (onfidoAnalyticsEvent.getType()){
                case FLOW: {
                  analytics.logEvent("onfido_flow", OnfidoExtKt.toBundle(onfidoAnalyticsEvent.getProperties()));
                }
                case SCREEN: {
                  analytics.logEvent("onfido_screen", OnfidoExtKt.toBundle(onfidoAnalyticsEvent.getProperties()));
                }
                case ACTION: {
                  analytics.logEvent("onfido_action", OnfidoExtKt.toBundle(onfidoAnalyticsEvent.getProperties()));
                }
                case ERROR: {
                  analytics.logEvent("onfido_error", OnfidoExtKt.toBundle(onfidoAnalyticsEvent.getProperties()));
                }
              }
            })
            .build();

    onfido.startActivityForResult(activityOwner.getActivityOrThrow(), REQUEST_ID, onfidoConfig)
```

#### Issue severity information (number of users/crashes if applicable):
Happen 100% cases

#### Other useful info:
- I can reproduce in production but not in development where minifying the app is disabled.

**Comment by niqo01** [comment]
Rolling back to onfido 16.3.2 fix the issue.

**Comment by niqo01** [comment]
Hello Musa, 
Our company name is Couchsurfing

**Comment by amd110** [comment]
我使用 flutter sdk 也遇到同样的问题，能不能尽快解决
