### ISSUE TITLE
unable to inflate CaptureActivity. Getting xml binary error. See error log.

### ISSUE THREAD

**Issue by akul1994** [onfido/onfido-android-sdk#3]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zoomcar.debug/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                    Caused by: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview
                                                                    Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(CaptureActivity.java:114)
                                                                       at android.app.Activity.performCreate(Activity.java:6672)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                    Caused by: java.lang.NoSuchMethodError: No static method zzC(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/app/com.zoomcar.debug-2/split_lib_dependencies_apk.apk:classes33.dex)
                                                                       at com.google.android.gms.vision.face.internal.client.zzf.zzb(Unknown Source)
                                                                       at com.google.android.gms.vision.face.internal.client.zzf.zza(Unknown Source)
                                                                       at com.google.android.gms.vision.face.internal.client.zzg.zzIi(Unknown Source)
                                                                       at com.google.android.gms.vision.face.internal.client.zzg.<init>(Unknown Source)
04-03 15:06:25.371 10144-10144/com.zoomcar.debug E/AndroidRuntime:     at com.google.android.gms.vision.face.FaceDetector$Builder.build(Unknown Source)
                                                                       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourceFactory.newInstance(CameraSourceFactory.java:26)
                                                                       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.<init>(CameraSourcePreview.java:58)
                                                                       	... 27 more

**Comment by rfreitas** [comment]
Hi,

This is due to having two different play services version on your app. The sdk's and your own.
You can write the module we are using to match your play services version
You can do so by putting it in your build.gradle.
```
dependencies {
   compile ('com.google.android.gms:play-services-vision:YOUR_PLAYSERVICES_VERSION')
}

**Comment by akul1994** [comment]
This worked. Thanks for the quick reply.

**Comment by akul1994** [comment]
Hey. getting an error response with the following:
REQTST ERROR: {"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"base":["The following reports have not been enabled for your account: identity. You can see the list of enabled reports using the /report_type_groups API endpoint. Please contact client-support@onfido.com if you have questions regarding your account setup."]}}}

I am adding report types as mentioned in the documentation with the following lines:

     currentReports.add(new Report(Report.Type.DOCUMENT));
       currentReports.add(new Report(Report.Type.IDENTITY));

However, the response says " The following reports have not been enabled for your account: identity"

**Comment by rfreitas** [comment]
Just to confirm, has this last issue been solved?If it's configuration `client-support@onfido.com` it's a good place to ask for help, if you know it's onfido api related (like this issue), `api@onfido.com` is also good.

**Comment by akul1994** [comment]
Yeah the issue has been resolved. Thanks for the help. Had a couple of more questions. is there anyway of customizing the type of documents the user can select to scan. Currently it shows three options - passport, license and national identity card. is there any way of customizing that. My requirement is to show only license and national identity card. Also is there any functionality to let the user pick an image from the phone gallery instead of clicking one.  the api allows us to attach any image but I couldnt find any way to do that through the sdk.

**Comment by rfreitas** [comment]
Quick answer is not possible on both.
For the first question it might be good to talk to your sales rep or account manager and mention my name. This way we can understand better your business needs.
For the second question, we don't do it and it's by design. We want to minimize digital fraud by forcing the user to take a picture with their camera. It's certainly not the only thing we do for fraud prevention, but it contributes overall.

**Comment by akul1994** [comment]
Alright. I'll speak to the concerned people and see what can be done. Thanks a lot for the help.
