### ISSUE TITLE
SDK Crashes on Samsung devices

### ISSUE THREAD

**Issue by cpetzel** [onfido/onfido-android-sdk#33]
#### What was the expected behaviour?
SDK doesn't crash on Samsung devices

#### What happened instead?
SDK Crashes

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.graphics.RectF.width()' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onPictureCaptured(Unknown Source:19)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview$2.onPictureTaken(Unknown Source:4)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSource$g.onPictureTaken(Unknown Source:26)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1106)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
#### Version info:

- `onfido-capture-sdk` version: 4.3.0
- Android API version(s): Android 8 

- `compileSdkVersion`: 27
- `targetSdkVersion`: 27
- `minSdkVersion`: 18
- Support library version (if applicable):

#### Steps to reproduce:

See stack trace here

http://crashes.to/s/ceb0ce2b828

#### Issue severity information (number of users/crashes if applicable):
dozens of crashes on misbehaving Samsung devices...

SM-G950F : 39%
SM-G955F : 21%
SM-G965F : 21%
SM-N950F : 17%
SM-G960F : 2%

#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @cpetzel . Thanks for flagging this, we will try to replicate it with a similar device and we will get back to you ASAP

**Comment by sergiomarquesmoura** [comment]
Hi @cpetzel . We're trying to replicate this on a Samsung Galaxy S9 running Android 8.0. However, we couldn't yet. In case you have been able to reproduce it, could you provide us the steps?

**Comment by sergiomarquesmoura** [comment]
This issue is duplicated, see #34 . Closing and continuing the thread on the other one
