### ISSUE TITLE
Error theme Android 9.0

### ISSUE THREAD

**Issue by ivanespitiac** [onfido/onfido-android-sdk#37]
#### Version info: lastd

- `onfido-capture-sdk` version: +
- Android API version(s): 28

- `compileSdkVersion`:28
- `targetSdkVersion`: 28
- `minSdkVersion`: 19
- Support library version (if applicable):

#### Onfido Flow initialization code:

final FlowStep[] flowStepsWithOptions = new FlowStep[]{
                FlowStep.WELCOME,
                FlowStep.CAPTURE_DOCUMENT,
                new FaceCaptureStep(FaceCaptureVariant.VIDEO),
                FlowStep.FINAL
        };
        OnfidoConfig onfidoConfig = OnfidoConfig.builder()
                .withApplicant("#############")
                .withToken("#########")
                .withCustomFlow(flowStepsWithOptions)
                .build();
        onfido = OnfidoFactory.create(this).getClient();
        onfido.startActivityForResult(this, 1, onfidoConfig);

#### Issue severity information (number of users/crashes if applicable):

chash in debug

#### Additional LogCat output:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: albo.onfidotest.com, PID: 4512
    java.lang.RuntimeException: Unable to start activity ComponentInfo{albo.onfidotest.com/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
        at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate(Unknown Source:5)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)

#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @ivanespitiac . Is there a chance that you defined an `OnfidoActivityTheme` in your app resources that can be overriding ours?

**Comment by ivanespitiac** [comment]
Hi @sergiomarquesmoura my file stlyes.xml is this

<img width="535" alt="captura de pantalla 2018-10-18 a la s 10 59 19" src="https://user-images.githubusercontent.com/26120138/47167831-00496380-d2c5-11e8-8be9-a8105e4a15a4.png">

it's an application for test SDK.

**Comment by ivanespitiac** [comment]
@sergiomarquesmoura no, with last update works, thanks.
