### ISSUE TITLE
Intermittent crash

### ISSUE THREAD

**Issue by jbarat** [onfido/onfido-android-sdk#4]
I'm having an intermittent crash which I can't seem to be able to reproduce.
I'm using version 1.0.0 and migrated from 0.7.1-rc1 when this issue started.
It works sometimes. This happens after I selected my document type.

My code:
```
...
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        onfido = OnfidoFactory.create(this).getClient();
    }
    
    @Override
    public void startVerificationProcess() {
        onfido.startActivityForResult(this, 1, getConfig(user));
    }
    
    private OnfidoConfig getConfig(IdentityVerificationUser user) {
        return OnfidoConfig.builder()
                .withToken(environmentConfig.getOnfidoKey())
                .withCustomFlow(getFlowSteps())
                .withApplicant(identityApplicantMapper.map(user))
                .build();
    }

    private FlowStep[] getFlowSteps() {
        return new FlowStep[]{
                FlowStep.CAPTURE_DOCUMENT,              //Document Capture Step
                FlowStep.CAPTURE_FACE,                  //Face Capture Step
        };
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        onfido.handleActivityResult(resultCode, data, new Onfido.OnfidoResultListener() {
            @Override
            public void userCompleted(Applicant applicant, Captures captures) {
                showIdentityVerificationFinishedFragment(true, applicant.getId());
            }

            @Override
            public void userExited(ExitCode exitCode, Applicant applicant) {

            }
        });
    }

...
```

This is my stacktrace:

```FATAL EXCEPTION: main
    Process: com.<removed>.debug, PID: 17654
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2017.2.0f3
    Device model      : motorola Moto G (5) Plus
    Device fingerprint: motorola/potter_n/potter_n:7.0/NPNS25.137-33-11/11:user/release-keys

    Caused by: java.lang.RuntimeException: startPreview failed
    at android.hardware.Camera.startPreview(Native Method)
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSource.a(Unknown Source)
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSource.start(Unknown Source)
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startWithException(Unknown Source)
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.start(Unknown Source)
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$6.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6123)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by sergiomarquesmoura** [comment]
Hey @jbarat 
Is the device where it's happening rooted? Or is it happening in non-rooted devices?

**Comment by jbarat** [comment]
it's on a non rooted Moto G5 Plus. Android version 7.0.

**Comment by jbarat** [comment]
I tried the same code on a few different phones and it only crashes on the Moto G5 Plus. 
Looking back in Crashlitics I can see only one crash like this happening with the OnFido sdk version 0.7.1-rc1 on a Moto G5 Plus phone. This might be something very phone specific.

**Comment by rfreitas** [comment]
It would be good to monitor this crash when you roll newer versions.
The camera API is known for high inconsistency among vendors. We can code defensively for it, but it doesn't mean the user we will be able to take a picture in those cases.

**Comment by sergiomarquesmoura** [comment]
Hello @jbarat !
Starting on version `3.0.0`, we added an `onError()` callback that is returned to the developer in case an error that we cannot recover from (like this one) happens. For more information, please check our changelog
