### ISSUE TITLE
SDK crashes on Samsung devices with Android 7

### ISSUE THREAD

**Issue by SemenovAlexander** [onfido/onfido-android-sdk#41]
#### What was the expected behaviour?
SDK doesn't crash on any supported device

#### What happened instead?
App crashes in production on Samsung S8 and S8 plus devices running Android 7.0 in SDK code
See report for more info:
http://crashes.to/s/1214219169a

#### Version info:

- `onfido-capture-sdk` version: 4.4.0
- Android API version(s): 7.0 

- `compileSdkVersion`: 26
- `targetSdkVersion`: 26
- `minSdkVersion`: 19
- Support library version (if applicable):

#### Steps to reproduce:
Unclear, crash report comes from fabric, probably just try to pass verification

#### Issue severity information (number of users/crashes if applicable):
2 users / 11 crashes for 24 hours

#### Additional LogCat output:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.graphics.RectF.width()' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onPictureCaptured(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview$2.onPictureTaken(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.face.CameraSource$PictureDoneCallback.onPictureTaken(Unknown Source)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1115)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

#### Other useful info:
http://crashes.to/s/1214219169a

**Comment by sergiomarquesmoura** [comment]
Hi @SemenovAlexander . Thanks for flagging this! 
We just released `4.5.1` which addresses this issue. Please try it out when you have a chance.
