### ISSUE TITLE
Onfido 4.5.1 crash on startVideo

### ISSUE THREAD

**Issue by ZebpayDipen** [onfido/onfido-android-sdk#43]
#### What was the expected behaviour?
Selfie video should open 
#### What happened instead?
Selfie video surface is not opening and also not asking for the permission.
Stuck at that and then crash
#### Version info:
4.5.1
- `onfido-capture-sdk` version: 4.5.1
- Android API version(s): 6

- `compileSdkVersion`: 26
- `targetSdkVersion`: 26
- `minSdkVersion`:15
- Support library version (if applicable):

#### Steps to reproduce:
Just configure the 4.5.1 and started onfido video and crashed

#### Onfido Flow initialization code:
Process: zebpay.Application, PID: 17152
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.startVideo(com.onfido.android.sdk.capture.ui.camera.face.MediaCaptureCallback)' on a null object reference
        at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startVideo(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startVideoCapture(Unknown Source:86)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$startVideoCapture(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$inflateCaptureButton$$inlined$apply$lambda$1.onClick(Unknown Source:27)
        at android.view.View.performClick(View.java:6297)
        at android.view.View$PerformClick.run(View.java:24797)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
#### Additional LogCat output:
Process: zebpay.Application, PID: 17152
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.startVideo(com.onfido.android.sdk.capture.ui.camera.face.MediaCaptureCallback)' on a null object reference
        at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startVideo(Unknown Source:2)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startVideoCapture(Unknown Source:86)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$startVideoCapture(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$inflateCaptureButton$$inlined$apply$lambda$1.onClick(Unknown Source:27)
        at android.view.View.performClick(View.java:6297)
        at android.view.View$PerformClick.run(View.java:24797)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @ZebpayDipen ! Could you reproduce this crash? If so, is this happening on one specific device or several models?

**Comment by ZebpayDipen** [comment]
It is happening with the several devices and Yes I have reproduced the bug
like 4-5 times where I have just changed the version to 4.5.1 from 4.4.0

**Comment by sergiomarquesmoura** [comment]
Could you list us the devices where you could spot the issue on?

**Comment by sergiomarquesmoura** [comment]
Is it always happening on the Redmi Note 4? We have that device as a testing one and I am not being able to reproduce it at the moment
