### ISSUE TITLE
Onfido crashing under react-native

### ISSUE THREAD

**Issue by vnvs** [onfido/onfido-android-sdk#49]
#### What was the expected behaviour?
The flow whole sdk flow happens

#### What happened instead?
The flow crashes when I click on on drivers license, national identity card or residence permit card. It also happens when I click on 'My passport is readable' on the Passport flow.

#### Version info:
- `onfido-capture-sdk` version: 4.7.0
- Android API version(s): 26
- `compileSdkVersion`: 26
- `targetSdkVersion`:26
- `minSdkVersion`:21

Btw, it's running under react native.

#### Steps to reproduce:
Open the APP, start the the onFidoSDK, click on driver's license.

#### Onfido Flow initialization code:

03-12 10:24:13.260 21213 21213 E AndroidRuntime: java.lang.UnsupportedOperationException: This is not supported, use MenuItemCompat.setOnActionExpandListener()
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v7.view.menu.MenuItemImpl.setOnActionExpandListener(MenuItemImpl.java:743)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at com.onfido.android.sdk.capture.ui.country_selection.CountrySelectionFragment.onCreateOptionsMenu(Unknown Source:102)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2353)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3088)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:319)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:363)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:693)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-12 10:24:13.260 21213 21213 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-12 10:24:13.264  1821  4308 W ActivityManager:   Force finishing activity com.app.app.debug/com.onfido.android.sdk.capture.ui.OnfidoActivity

**Comment by sergiomarquesmoura** [comment]
Hi @vnvs . Could you also provide the following?
- Any support libraries being used, along with their version (if applicable)
- React native version

**Comment by vnvs** [comment]
of course!
react-native version: 0.57.5
Android support library 27.1.0

We are also using react-native-navigation

**Comment by sergiomarquesmoura** [comment]
Hi @vnvs . There could be runtime crashes due to the fact that you're picking different major versions for the `compileSdkVersion` and support library version. Could you check that if you bump your compile sdk version to 27 (or downgrade your support lib version to 26), this issue is still present?

**Comment by sergiomarquesmoura** [comment]
Closing due to inactivity. @vnvs tell me if you're still seeing the issue after my suggestions
