### ISSUE TITLE
Unable to start OnfidoActivity (Caused by: java.lang.IllegalArgumentException: either category or name must be provided.)

### ISSUE THREAD

**Issue by slicepay11** [onfido/onfido-android-sdk#53]
#### What was the expected behaviour?
Trying to launch the face check. 

#### What happened instead?
Getting crash on launching OnfidoActivity.

#### Version info:

- `onfido-capture-sdk` version: 4.7.0
- Android API version(s): 23

- `compileSdkVersion`: 28
- `targetSdkVersion`:
- `minSdkVersion`: 19
- Support library version (if applicable): 28.0.0

#### Steps to reproduce:
Try to launch onfidoActivity after creating applicant.

#### Onfido Flow initialization code:
                JsonObject jsonObject = jsonElement.getAsJsonObject();
                String applicantId = jsonObject.get("id").getAsString();
                OnfidoConfig.Builder onfidoConfigBuilder =
                        OnfidoConfig.builder().withApplicant(applicantId)
                                .withToken("ONFIDO_TOKEN");

                if (flowSteps != null) {
                    onfidoConfigBuilder.withCustomFlow(flowSteps);
                }

                OnfidoConfig onfidoConfig = onfidoConfigBuilder.build();
                onfido.startActivityForResult(getActivity(), 1, onfidoConfig);

#### Additional LogCat output:
    java.lang.RuntimeException: Unable to start activity ComponentInfo{indwin.c3.shareapp.dev/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.IllegalArgumentException: either category or name must be provided.
2019-03-28 16:37:56.992 2250-2250/indwin.c3.shareapp.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: indwin.c3.shareapp.dev, PID: 2250
    java.lang.RuntimeException: Unable to start activity ComponentInfo{indwin.c3.shareapp.dev/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.IllegalArgumentException: either category or name must be provided.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.IllegalArgumentException: either category or name must be provided.
        at com.segment.analytics.Analytics.screen(Analytics.java:681)
        at com.segment.analytics.Analytics.screen(Analytics.java:642)
        at com.segment.analytics.Analytics.recordScreenViews(Analytics.java:436)
        at com.segment.analytics.Analytics$3.onActivityStarted(Analytics.java:310)
        at android.app.Application.dispatchActivityStarted(Application.java:207)
        at android.app.Activity.onStart(Activity.java:1192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:614)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6683)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6251) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 

#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @slicepay11 . This is an issue with the interaction of the Segment Analytics SDK and our activities. We already identified it and a fix is on the way. Will comment here once it's live

**Comment by sergiomarquesmoura** [comment]
Hi @slicepay11 .
We just release version [4.8.0](https://github.com/onfido/onfido-android-sdk/releases/tag/4.8.0) which solves this issue.
Test it out when you have the chance please
