### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Platform"

### ISSUE THREAD

**Issue by andreluizreis** [onfido/onfido-android-sdk#54]
#### What was the expected behaviour?
Not crash. 

#### What happened instead?
It's crashing after taking the photo of the ID. 

#### Version info:

- `onfido-capture-sdk` version: 4.8.0
- Android API version(s): 21 (I was testing now)
- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 16
- Support library version (if applicable):
    implementation "com.google.android.material:material:1.0.0"
    implementation "androidx.appcompat:appcompat:1.0.2"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.browser:browser:1.0.0"
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.vectordrawable:vectordrawable:1.0.1"
    implementation "androidx.core:core:1.0.1"
    implementation "androidx.annotation:annotation:1.0.2"
    implementation 'androidx.preference:preference:1.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation 'com.google.dagger:dagger:2.20'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.20'

    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'

   implementation 'com.onfido.sdk.capture:onfido-capture-sdk:4.8.0'
    implementation ('com.google.android.gms:play-services-base:16.0.1') {
        exclude group: 'com.android.support' 
    }

#### Steps to reproduce:
After taking the photo of the driver license the app is crashing. 

#### Onfido Flow initialization code:
```
private fun initOnfidoSDK(applicantId: String) {
        mOnfido = OnfidoFactory.create(mContext).client
        
        val defaultStepsWithWelcomeScreen = arrayOf(
            FlowStep.WELCOME, //Welcome step with a step summary, Optional
            FlowStep.CAPTURE_DOCUMENT, //Document Capture Step
            FlowStep.CAPTURE_FACE,     //Face Capture Step
            FlowStep.FINAL             //Final Screen Step, Optional
        )
        
        // Onfido Key
        val onfidoKey: String = Config.unhide(Config.getOnfidoKey(BuildConfig.FLAVOR))
        
        // Onfido configuration
        val onfidoConfig: OnfidoConfig = OnfidoConfig.builder()
            .withCustomFlow(defaultStepsWithWelcomeScreen)
            .withToken("test_AAAAAAAAAAAAAAAAAAAAAAAAAA")
            .withApplicant(applicantId)
            .build()
        
        mOnfido.startActivityForResult(mActivity, ONFIDO_REQUEST_CODE, onfidoConfig)
    }
```
#### Additional LogCat output:
```
04-18 15:38:31.311 20129-21130/com.xxx.xxx.stage E/FirebaseInstanceId: Token retrieval failed: INVALID_SENDER
04-18 15:38:31.321 20129-20139/com.xxx.xxx.stage E/BufferQueueProducer: [unnamed-20129-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=5 undequeued=1)
04-18 15:38:34.731 20129-21228/com.xxx.xxx.stage E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.xxx.xxx.stage, PID: 20129
    java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/Platform;
        at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:112)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:160)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.onfido.api.client.OnfidoFetcher$AuthTokenInterceptor.intercept(OnfidoFetcher.java:129)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Platform" on path: DexPathList[[zip file "/data/app/com.xxx.xxx.stage-3/base.apk", zip file "/data/app/com.xxx.xxx.stage-3/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxxx.stage-3/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:112) 
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:160) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at com.onfido.api.client.OnfidoFetcher$AuthTokenInterceptor.intercept(OnfidoFetcher.java:129) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: okhttp3.internal.Platform
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

```
#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @andreluizreis ! Could you add the following line to your dependencies block?

`implementation "com.squareup.okhttp3:logging-interceptor:$yourOkHttpVersion"`

This happens because your app is overriding our OkHttp version, and since we also rely on the logging interceptor, the versions won't match

**Comment by andreluizreis** [comment]
Thank you @sergiomarquesmoura, it's working now.

**Comment by andreluizreis** [comment]
@sergiomarquesmoura, I am using the solution that you suggested to me: 
```
implementation "com.squareup.okhttp3:logging-interceptor:3.14.1"
``` 

The problem now is my Interceptor crashes every time that I am Retrying a call. 
It will crash in this line `response = chain.proceed(request);`.

The error: 
`cannot make a new request because the previous response is still open: please call response.close()`

```
public Response intercept(@NonNull Interceptor.Chain chain) throws IOException {
        Request request = chain.request();
        
        // try the request
        Response response = chain.proceed(request);
        
        // Check response status
        int tryCount = 0;
        while (isFailure(response) && tryCount < 3) {
            // Try again
            tryCount++;
            
            // retry the request
            response = chain.proceed(request);
        }
        
        // otherwise just pass the original response on
        return response;
    }
``` 

I guess it's because the new version of OkHttp3 is handling a little different than the version inside Retrofit. But they are supposed to be the same version. I checked on Maven repository. 

What I am doing now to turn around this issue is: 
```
public Response intercept(@NonNull Interceptor.Chain chain) throws IOException {
        Request request = chain.request();
        
        // try the request
        Response response = chain.proceed(request);
        
        // Check response status
        int tryCount = 0;
        while (isFailure(response) && tryCount < 3) {
            // Try again
            tryCount++;
            
            // retry the request
            try {
                response.close();
                Request retry = request.newBuilder().build();
                response = chain.proceed(retry);
            } catch(Exception ex) {
                SentryHelper.sendException(ex);
                return response;
            }
        }
        
        // otherwise just pass the original response on
        return response;
    }
```
