### ISSUE TITLE
Crash while starting OnFido from a Fragment

### ISSUE THREAD

**Issue by npike** [onfido/onfido-android-sdk#56]
#### What was the expected behaviour?
OnFido activity is started at document capture step.

#### What happened instead?
Crashes

#### Version info:

- `onfido-capture-sdk` version: 4.8.0
- Android API version(s): 28

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21
- Support library version (if applicable):
androidx 

#### Steps to reproduce:

Trying to start the flow from within a Fragment, by calling `createIntent()` on my onfido instance, and then startActivityForResult inside my fragment.

#### Onfido Flow initialization code:

```kotlin
val onfido = OnfidoFactory.create(requireActivity()).client

val onfidoFlow = arrayOf(FlowStep.CAPTURE_DOCUMENT, //Document Capture Step
                FlowStep.CAPTURE_FACE, //Face Capture Step
                FlowStep.FINAL                          //Final Screen Step, Optional
)

val config = OnfidoConfig.builder()
                .withCustomFlow(onfidoFlow)
                .withToken("REDACTED")
                .withApplicant("REDACTED")
                .build()

val intent = onfido.createIntent(config)
startActivityForResult(
                intent,
                137
)
```

#### Additional LogCat output:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.phunware.wallet/com.onfido.android.sdk.capture.ui.OnfidoActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.KotlinNullPointerException
        at com.onfido.android.sdk.capture.common.SdkController.getSdkComponent(Unknown Source:18)
        at com.onfido.android.sdk.capture.common.SdkController.getSdkComponent$default(Unknown Source:15)
        at com.onfido.android.sdk.capture.ui.BaseActivity.attachBaseContext(Unknown Source:13)
        at android.app.Activity.attach(Activity.java:7051)
```
#### Other useful info:
_screenshots, videos, etc._

**Comment by npike** [comment]
For what it's worth, it seems I can call the following before calling `createIntent` and everything is happy again.

```
SdkController.instance.init(fragment.requireContext(), config)
```

**Comment by jlmcdonnell** [comment]
```
SdkController.instance.init(fragment.requireContext(), config)
```

This seems to be the key thing, as starting the Onfido flow from _anywhere_ causes that crash unless I add this line.

**Comment by sergiomarquesmoura** [comment]
Hi @npike @jlmcdonnell 
To start the flow, you should use our method `Onfido.startActivityFromResult()` and you don't need to call any method in the `SdkController` yourselves. However, I understand that this way you cannot start the flow from a `Fragment`, but we will consider adding this in the near future
