### ISSUE TITLE
Documentation does not specify requirement for OkHttp

### ISSUE THREAD

**Issue by jlmcdonnell** [onfido/onfido-android-sdk#57]
#### What was the expected behaviour?

The README should speficy _all_ of the SDKs third party requirements

#### What happened instead?

I receive a crash because I have not included OkHttp, which was not specified

#### Version info:

- `onfido-capture-sdk` version: 4.8.0
- Android API version(s): all
- `compileSdkVersion`: all
- `targetSdkVersion`: all
- `minSdkVersion`: all
- Support library version (if applicable): all

#### Additional LogCat output:

```
2019-04-29 14:38:21.140 4792-5028/########## E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: ############, PID: 4792
    java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/Platform;
        at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:112)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:160)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.onfido.api.client.OnfidoFetcher$AuthTokenInterceptor.intercept(OnfidoFetcher.java:129)
```

**Comment by jlmcdonnell** [comment]
It looks like there is mention of it in the [react native guide](https://github.com/onfido/onfido-android-sdk/blob/master/documentation/ReactNative.md)
