### ISSUE TITLE
crash on Oneplus android version 9

### ISSUE THREAD

**Issue by jpnapps** [onfido/onfido-android-sdk#58]
**android.view.InflateException: Binary XML file line #15: Binary XML file line #15: You must supply a layout_width attribute.**
    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #15: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:798)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7766)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7958)
        at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java:1269)
        at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1090)
        at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:83)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        **at com.onfido.android.sdk.capture.ui.LoadingFragment.onCreateView(Unknown Source:3)**

**Comment by sergiomarquesmoura** [comment]
Hi @jpnapps . The issue template we provide is really useful for us to gather the necessary information to address the issue. Please edit the issue according to it

**Comment by sergiomarquesmoura** [comment]
Hi again @jpnapps . The only reason I can think of, for this to happen, is you having a style named `OnfidoTextStyle` which is overriding our own style. Could you try to search for that and see if a renaming of such style helps?

**Comment by sergiomarquesmoura** [comment]
Closing due to inactivity
