### ISSUE TITLE
Crash on build with proguard

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#6]
02-10 11:38:44.466 6184-6184/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.wirex.dev, PID: 6184
                                                 java.lang.AssertionError: java.lang.NoSuchFieldException: PASSPORT
                                                     at com.google.gson.internal.bind.i$a.<init>(TypeAdapters.java:791)
                                                     at com.google.gson.internal.bind.TypeAdapters$30.a(TypeAdapters.java:817)
                                                     at com.google.gson.Gson.a(Gson.java:423)
                                                     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:115)
                                                     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:164)
                                                     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:100)
                                                     at com.google.gson.Gson.a(Gson.java:423)
                                                     at retrofit2.converter.gson.GsonConverterFactory.responseBodyConverter(GsonConverterFactory.java:64)
                                                     at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
                                                     at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
                                                     at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736)
                                                     at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169)
                                                     at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
                                                     at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
                                                     at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                     at com.onfido.api.client.$Proxy40.upload(Unknown Source)
                                                     at com.onfido.api.client.m.a(UploadDocumentAPI.java:45)
                                                     at com.onfido.api.client.k.a(OnfidoAPIImpl.java:66)
                                                     at com.onfido.android.sdk.capture.ui.camera.j.b(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.j.a(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.d(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.h(Unknown Source)
                                                     at com.onfido.android.sdk.capture.ui.camera.ConfirmationStepButtons$b.onClick(Unknown Source)
                                                     at android.view.View.performClick(View.java:5638)
                                                     at android.view.View$PerformClick.run(View.java:22444)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:159)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6139)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.NoSuchFieldException: PASSPORT
                                                     at java.lang.Class.getField(Class.java:1549)
                                                     at com.google.gson.internal.bind.i$a.<init>(TypeAdapters.java:780)
                                                     at com.google.gson.internal.bind.TypeAdapters$30.a(TypeAdapters.java:817) 
                                                     at com.google.gson.Gson.a(Gson.java:423) 
                                                     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:115) 
                                                     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:164) 
                                                     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(ReflectiveTypeAdapterFactory.java:100) 
                                                     at com.google.gson.Gson.a(Gson.java:423) 
                                                     at retrofit2.converter.gson.GsonConverterFactory.responseBodyConverter(GsonConverterFactory.java:64) 
                                                     at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330) 
                                                     at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313) 
                                                     at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736) 
                                                     at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169) 
                                                     at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170) 
                                                     at retrofit2.Retrofit$1.invoke(Retrofit.java:147) 
                                                     at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
                                                     at com.onfido.api.client.$Proxy40.upload(Unknown Source) 
                                                     at com.onfido.api.client.m.a(UploadDocumentAPI.java:45) 
                                                     at com.onfido.api.client.k.a(OnfidoAPIImpl.java:66) 
                                                     at com.onfido.android.sdk.capture.ui.camera.j.b(Unknown Source) 
                                                     at com.onfido.android.sdk.capture.ui.camera.j.a(Unknown Source) 
                                                     at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.d(Unknown Source) 
                                                     at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.h(Unknown Source) 
                                                     at com.onfido.android.sdk.capture.ui.camera.ConfirmationStepButtons$b.onClick(Unknown Source) 
                                                     at android.view.View.performClick(View.java:5638) 
                                                     at android.view.View$PerformClick.run(View.java:22444) 
                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at android.os.Looper.loop(Looper.java:159) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6139) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by sergiomarquesmoura** [comment]
Hi @shaubert ! 
Have you tried to add any proguard rules in your rules file to overcome this? i.e.
`-keep public class com.onfido.android.sdk.** {
    public protected *;
}`

Anyway, will investigate this on our side and update you later.

**Comment by shaubert** [comment]
Yes, keeping of sdk classes did the trick. But these rules have to be provided in readme or be shipped in proguard config file inside aar.

**Comment by sergiomarquesmoura** [comment]
We will ship those rules soon with the SDK

**Comment by OleksandrGrument** [comment]
Hi, I faced with the same issue, but -keep public class com.onfido.android.sdk.** { public protected *; } doesn't help. ` FATAL EXCEPTION: main
                                                                          Process: com.phlatbed.phlatbedapp, PID: 31087
                                                                          java.lang.AssertionError: java.lang.NoSuchFieldException: PASSPORT
                                                                              at com.google.gson.internal.bind.i$a.<init>(Unknown Source)
                                                                              at com.google.gson.internal.bind.TypeAdapters$30.a(Unknown Source)
                                                                              at com.google.gson.d.a(Unknown Source)
                                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source)
                                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source)
                                                                              at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.a(Unknown Source)
                                                                              at com.google.gson.d.a(Unknown Source)
                                                                              at retrofit2.converter.gson.GsonConverterFactory.responseBodyConverter(Unknown Source)
                                                                              at retrofit2.Retrofit.nextResponseBodyConverter(Unknown Source)
                                                                              at retrofit2.Retrofit.responseBodyConverter(Unknown Source)
                                                                              at retrofit2.ServiceMethod$Builder.createResponseConverter(Unknown Source)
                                                                              at retrofit2.ServiceMethod$Builder.build(Unknown Source)
                                                                              at retrofit2.Retrofit.loadServiceMethod(Unknown Source)
                                                                              at retrofit2.Retrofit$1.invoke(Unknown Source)
                                                                              at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                              at com.onfido.api.client.$Proxy9.upload(Unknown Source)
                                                                              at com.onfido.api.client.m.a(Unknown Source)
                                                                              at com.onfido.api.client.k.a(Unknown Source)
                                                                              at com.onfido.android.sdk.capture.ui.camera.a.b(Unknown Source)
                                                                              at com.onfido.android.sdk.capture.ui.camera.a.a(Unknown Source)
                                                                              at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.b(Unknown Source)
                                                                              at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.confirmed(Unknown Source)
                                                                              at com.onfido.android.sdk.capture.ui.camera.ConfirmationStepButtons$a.onClick(Unknown Source)
                                                                              at android.view.View.performClick(View.java:5610)
                                                                              at android.view.View$PerformClick.run(View.java:22265)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                           Caused by: java.lang.NoSuchFieldException: PASSPORT`

the version  is - `compile 'com.onfido.sdk.capture:onfido-capture-sdk:2.3.0'`

Do anyone have suggetions?

**Comment by sergiomarquesmoura** [comment]
Hello @OleksandrGrument .
Please have a look here: #15

**Comment by OleksandrGrument** [comment]
@sergiomarquesmoura Thanks, didn't saw this topic. It helped me.
