### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#8]
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{26eabd13 position=74 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{2e2cf0a0 VFED.... ......I. 0,0-480,423 #7f0a0137 app:id/countriesList}, adapter:com.onfido.android.sdk.capture.ui.country_selection.CountrySelectionAdapter@8067905, layout:android.support.v7.widget.LinearLayoutManager@27f3d5a, context:com.onfido.android.sdk.capture.ui.OnfidoActivity@328928de
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5447)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5629)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1171)
       at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:856)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:875)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16001)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2483)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2180)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6598)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by shaubert** [comment]
Devices
samsung 45%
SPA Condor Electronics 9%
TECNO 9%
TCL 5%
Other…32%

Galaxy J7(2016) 15%
Galaxy Note3 10%
Galaxy Grand Prime 10%
SM-A720F 10%
Galaxy J15 %

Operating Systems
7 37%
5 27%
6 27%
4 9%

**Comment by sergiomarquesmoura** [comment]
Hey @shaubert . From what I understood, you're currently using our `2.3.0` version. A newer `2.4.0` version was released last week, it might be worth to upgrade and check if the issue persist or not.

**Comment by sergiomarquesmoura** [comment]
Hello @shaubert !
This was fixed on the latest `3.0.0`

**Comment by bhargavms** [comment]
@sergiomarquesmoura could you explain what the problem was and how did you fix it?

**Comment by arifulislamiut** [comment]
How can i find the version?
