### ISSUE TITLE
Not compatible with firebase-perf library

### ISSUE THREAD

**Issue by krokyze** [onfido/onfido-android-sdk#80]
#### What was the expected behaviour?

I can use onfido sdk and firebae-perf in my project.

#### What happened instead?

- While building the app there's error:
`Error: Class content provided for type descriptor com.onfido.segment.analytics.M actually defines class com.onfido.segment.analytics.m`
- When I run the app and call onfido.startActivityForResult the app crashes with:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/onfido/segment/analytics/O;`

#### Version info:

- `onfido-capture-sdk` version: 5.0.1
- `firebase-perf` version: 19.0.0

- Android API version(s):

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21

#### Steps to reproduce:

Just add both libraries in project and call onfido.startActivityForResult.

#### Additional LogCat output:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/onfido/segment/analytics/O;
    at com.onfido.segment.analytics.Analytics$a.a()
    at com.onfido.android.sdk.capture.common.di.SdkModule.provideAnalyticsApi()
    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideAnalyticsApiFactory.get()
    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideAnalyticsApiFactory.get()
    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideAnalyticsInteractorFactory.get()
    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideAnalyticsInteractorFactory.get()
    at com.onfido.dagger.internal.a.get()
    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoPresenterFactory.get()
    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideOnfidoPresenterFactory.get()
    at com.onfido.android.sdk.capture.ui.OnfidoActivity_MembersInjector.injectMembers()
    at com.onfido.android.sdk.capture.ui.OnfidoActivity_MembersInjector.injectMembers()
    at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject()
    at com.onfido.android.sdk.capture.ui.OnfidoActivity.setupPresenterWith()
    at com.onfido.android.sdk.capture.ui.OnfidoActivity.onCreate()`

**Comment by kkosobudzki** [comment]
Same issue, I'm using `onfido-capture-sdk` version `5.1.0`. 

When performing `transformClassesWithDexBuilderForStagingDebug` I'm also getting another build error: `AGPBI: {"kind":"error","text":"Class content provided for type descriptor com.onfido.segment.analytics.M actually defines class com.onfido.segment.analytics.m","sources":[{}],"tool":"D8"}`

**Comment by gokhanaliccii** [comment]
@krokyze @kkosobudzki  Thanks for your patience, yesterday we released `5.2.0`. Could you please check our latest version and give us feedback

**Comment by kkosobudzki** [comment]
I can confirm there is no crash on `5.2.0` 🎉

**Comment by krokyze** [comment]
Thanks, 5.2.0 fixed the issue! 👍
