### ISSUE TITLE
Update the latest version of "onfido capture SDK" to enter the page and report an error.

### ISSUE THREAD

**Issue by 527179023** [onfido/onfido-android-sdk#84]
#### Version info:

- `onfido-capture-sdk` version:28
- Android API version(s):8.0

- `compileSdkVersion`:29
- `targetSdkVersion`:29
- `minSdkVersion`:16
- Support library version (if applicable):

#### Other useful info:
_screenshots, videos, etc._

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.onfido.sampleapp/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by gokhanaliccii** [comment]
@527179023  Could you provide more information(sdk-version, flow initialization code ) to reproduce the error ?
