### ISSUE TITLE
Internal KotlinNullPointerException 

### ISSUE THREAD

**Issue by jlmcdonnell** [onfido/onfido-android-sdk#88]
#### What was the expected behaviour?

No crash

#### What happened instead?

Crash!

Stack Trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.tokencard.app.android/com.onfido.android.sdk.capture.ui.OnfidoActivity}: kotlin.KotlinNullPointerException
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	 at android.os.Handler.dispatchMessage(Handler.java:106)
	 at android.os.Looper.loop(Looper.java:193)
	 at android.app.ActivityThread.main(ActivityThread.java:6718)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Caused by: 
kotlin.KotlinNullPointerException
	 at com.onfido.android.sdk.capture.common.SdkController.getSdkComponent(Unknown Source:18)
	 at com.onfido.android.sdk.capture.common.SdkController.getSdkComponent$default(Unknown Source:15)
	 at com.onfido.android.sdk.capture.ui.BaseActivity.attachBaseContext(Unknown Source:13)
	 at android.app.Activity.attach(Activity.java:7060)
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	 at android.os.Handler.dispatchMessage(Handler.java:106)
	 at android.os.Looper.loop(Looper.java:193)
	 at android.app.ActivityThread.main(ActivityThread.java:6718)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

#### Version info:

- `onfido-capture-sdk` version: 5.0.1
- Android API version(s): 28

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 24
- Support library version (if applicable): androidx / various versions - happy to give more info if needed.

#### Steps to reproduce:

Internal SDK call to `com.onfido.android.sdk.capture.common.SdkController.getSdkComponent`

#### Onfido Flow initialization code:

```
val config = OnfidoConfig.builder(context)
        .withCustomFlow(
          arrayOf(
            FlowStep.WELCOME,
            FlowStep.CAPTURE_DOCUMENT,
            FlowStep.CAPTURE_FACE
          )
        )
        .withApplicant(applicantID)
        .withToken(token)
        .build()
```

#### Issue severity information (number of users/crashes if applicable):

1 affected user, device:`motorola xt1685`, API 28

**Comment by gokhanaliccii** [comment]
@jlmcdonnell Thanks for reporting the issue, we'll investigate it. Once we have an update, we let you know.

**Comment by gokhanaliccii** [comment]
@jlmcdonnell Did you have chance to reproduce the crash ?

**Comment by gokhanaliccii** [comment]
@jlmcdonnell 

We have run tests internally and with our crowd testing partner with exactly the same device and version. Unfortunately we haven't been able to reproduce.

In case you are able to provide us with sample app and the steps to reproduce the crash on it, please do share it with us and we’ll reinvestigate
