### ISSUE TITLE
it jumps to FlowStep.CAPTURE_FACE, then the app crashes

### ISSUE THREAD

**Issue by 527179023** [onfido/onfido-android-sdk#89]
#### What was the expected behaviour?
		No crash		
#### What happened instead?
		Crash!
#### Version info:

- `onfido-capture-sdk` version: 5.1.0
- Android API version(s):28

- `compileSdkVersion`:28
- `targetSdkVersion`:28
- `minSdkVersion`:28
- Support library version (if applicable): com.android.support v4 or v7

#### Steps to reproduce:

	1. starting sdk
	2. correctly taking photos of front and back of identity card
	3. after successfully uploading back side of identity card, it jumps to module FlowStep.CAPTURE_FACE, then the app crashes
		
#### Onfido Flow initialization code:

	client = OnfidoFactory.create(this).getClient();

	final FlowStep[] flowStepsWithOptions = new FlowStep[]{
                new CaptureScreenStep(DocumentType.NATIONAL_IDENTITY_CARD, CountryAlternatives.NO_COUNTRY),
                FlowStep.CAPTURE_FACE,
        };

	OnfidoConfig onfidoConfig =
        OnfidoConfig.builder(OnfidoSdkActivity.this)
                .withSDKToken(sdkToken)
                .withCustomFlow(flowSteps)
                .build();
		
client.startActivityForResult(OnfidoSdkActivity.this, 1, onfidoConfig);

#### Issue severity information (number of users/crashes if applicable):

	1 affected user, device:HUAWEIPLK-TL01, API 23

#### Additional LogCat output:
	android.view.InflateException: Binary XML file line #68: Binary XML file line #68: Error inflating class ImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
        at com.onfido.android.sdk.capture.ui.BulletedMessageFragment.onCreateView()
        at com.onfido.android.sdk.capture.ui.FaceIntroFragment.onCreateView()
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)	

android.view.InflateException: Binary XML file line #68: Error inflating class ImageView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
        at com.onfido.android.sdk.capture.ui.BulletedMessageFragment.onCreateView() 
        at com.onfido.android.sdk.capture.ui.FaceIntroFragment.onCreateView() 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733) 
        at android.os.Handler.handleCallback(Handler.java:743) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5621) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.content.res.ComplexColorCompat.isStateful()' on a null object reference
        at android.support.graphics.drawable.VectorDrawableCompat$VFullPath.isStateful(VectorDrawableCompat.java:1942)
        at android.support.graphics.drawable.VectorDrawableCompat$VGroup.isStateful(VectorDrawableCompat.java:1650)
        at android.support.graphics.drawable.VectorDrawableCompat$VPathRenderer.isStateful(VectorDrawableCompat.java:1398)
        at android.support.graphics.drawable.VectorDrawableCompat$VectorDrawableCompatState.isStateful(VectorDrawableCompat.java:1134)
        at android.support.graphics.drawable.VectorDrawableCompat.isStateful(VectorDrawableCompat.java:525)
        at android.widget.ImageView.updateDrawable(ImageView.java:888)
        at android.widget.ImageView.setImageDrawable(ImageView.java:472)
        at android.support.v7.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:100)
        at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:61)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:765)

**Comment by bartzet** [comment]
Hello @527179023.

Thank you for reporting this.

Seems like this is a duplicated issue. We have already had this raised here: https://github.com/onfido/onfido-android-sdk/issues/86

We are currently investigating the issue and we will update you once we release the fix for it.

**Comment by 527179023** [comment]
ok, thank you.

**Comment by bartzet** [comment]
Hi @527179023.

We have run tests internally and with our crowd testing partner with exactly the same device and version and we haven't been able to reproduce.

From the given logs we are not able to tell what the problem might be.

In case you are able to provide us with better logs, please feel free to open a separate issue.
