### ISSUE TITLE
KotlinNullPointerException at SdkController.getSdkComponent

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#9]
Caused by kotlin.KotlinNullPointerException
       at com.onfido.android.sdk.capture.common.SdkController.getSdkComponent(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.b(Unknown Source)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:5264)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by shaubert** [comment]
Devices
samsung 49%
HUAWEI 11%
LG Electronics 7%
condor 7%
Other… 26%

Galaxy J1 52%
Galaxy S5 8%
SM-G532F 8%
Galaxy A3(2016) 8%
Galaxy J1 Mini 8%

Operating Systems
4 44%
6 22%
5 19%
7 15%

**Comment by sergiomarquesmoura** [comment]
Hey @shaubert . From what I understood, you're currently using our `2.3.0` version. A newer `2.4.0` version was released last week, it might be worth to upgrade and check if the issues persist or not.

**Comment by seewah** [comment]
Fixed in version `3.0.0`. See [changelog](https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD#300---2018-04-05)
