### ISSUE TITLE
java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0;

### ISSUE THREAD

**Issue by 527179023** [onfido/onfido-android-sdk#90]
#### What was the expected behaviour?
		after entering the camera, we tapped on the click button to take a picture,  then the app crashes	
#### What happened instead?
		Crash!
#### Version info:

- `onfido-capture-sdk` version: 5.1.0
- Android API version(s):28

- `compileSdkVersion`:28
- `targetSdkVersion`:28
- `minSdkVersion`:14
- Support library version (if applicable): com.android.support v4 or v7

#### Steps to reproduce:

	1. starting sdk
	2. after entering the camera, we tapped on the click button to take a picture,  then the app crashes
		
#### Onfido Flow initialization code:

	client = OnfidoFactory.create(this).getClient();

	final FlowStep[] flowStepsWithOptions = new FlowStep[]{
                new CaptureScreenStep(DocumentType.NATIONAL_IDENTITY_CARD, CountryAlternatives.NO_COUNTRY),
                FlowStep.CAPTURE_FACE,
        };

	OnfidoConfig onfidoConfig =
        OnfidoConfig.builder(OnfidoSdkActivity.this)
                .withSDKToken(sdkToken)
                .withCustomFlow(flowSteps)
                .build();
		
client.startActivityForResult(OnfidoSdkActivity.this, 1, onfidoConfig);

#### Issue severity information (number of users/crashes if applicable):
	1 affected user, device:Xiaomi 8, API 28
#### Additional LogCat output:
	Process: com.pundix.xwallet, PID: 21498
    java.lang.RuntimeException: Unable to stop activity {com.pundix.xwallet/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4204)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4174)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4249)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:849)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1988)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1977)
        at com.google.android.gms.internal.clearcut.zzab.zza(Unknown Source:32)
        at com.google.android.gms.internal.clearcut.zzae.zzl(Unknown Source:34)
        at com.google.android.gms.internal.clearcut.zzae.get(Unknown Source:26)
        at com.google.android.gms.internal.clearcut.zzp.zza(Unknown Source:17)
        at com.google.android.gms.clearcut.ClearcutLogger$LogEventBuilder.log(Unknown Source:74)
        at com.google.android.gms.internal.firebase_ml.zznv.zza(Unknown Source:55)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.<init>(Unknown Source:21)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.zza(Unknown Source:13)
        at com.google.firebase.ml.vision.FirebaseVision.getVisionFaceDetector(Unknown Source:15)
        at com.onfido.android.sdk.capture.face.FaceDetector.getFaceDetector(Unknown Source:10)
        at com.onfido.android.sdk.capture.face.FaceDetector.access$getFaceDetector(Unknown Source:0)
        at com.onfido.android.sdk.capture.face.FaceDetector$fastDetector$2.invoke(Unknown Source:6)
        at com.onfido.android.sdk.capture.face.FaceDetector$fastDetector$2.invoke(Unknown Source:0)
        at kotlin.o.getValue(LazyJVM.kt:74)
        at com.onfido.android.sdk.capture.face.FaceDetector.getFastDetector(Unknown Source:7)
        at com.onfido.android.sdk.capture.face.FaceDetector.close(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stopFaceTracking(Unknown Source:9)
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stop(Unknown Source:35)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onStop(Unknown Source:8)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1433)
        at android.app.Activity.performStop(Activity.java:7489)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4196)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4174) 
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4249) 
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
        at android.content.IContentService$Stub.onTransact(IContentService.java:76)
        at com.android.server.content.ContentService.onTransact(ContentService.java:262)
2019-11-12 16:45:51.841 21498-21498/? E/UncaughtException: java.lang.RuntimeException: Unable to stop activity {com.pundix.xwallet/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4204)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4174)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4249)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:849)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1988)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1977)
        at com.google.android.gms.internal.clearcut.zzab.zza(Unknown Source:32)
        at com.google.android.gms.internal.clearcut.zzae.zzl(Unknown Source:34)
        at com.google.android.gms.internal.clearcut.zzae.get(Unknown Source:26)
        at com.google.android.gms.internal.clearcut.zzp.zza(Unknown Source:17)
        at com.google.android.gms.clearcut.ClearcutLogger$LogEventBuilder.log(Unknown Source:74)
        at com.google.android.gms.internal.firebase_ml.zznv.zza(Unknown Source:55)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.<init>(Unknown Source:21)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.zza(Unknown Source:13)
        at com.google.firebase.ml.vision.FirebaseVision.getVisionFaceDetector(Unknown Source:15)
        at com.onfido.android.sdk.capture.face.FaceDetector.getFaceDetector(Unknown Source:10)
        at com.onfido.android.sdk.capture.face.FaceDetector.access$getFaceDetector(Unknown Source:0)
        at com.onfido.android.sdk.capture.face.FaceDetector$fastDetector$2.invoke(Unknown Source:6)
        at com.onfido.android.sdk.capture.face.FaceDetector$fastDetector$2.invoke(Unknown Source:0)
        at kotlin.o.getValue(LazyJVM.kt:74)
        at com.onfido.android.sdk.capture.face.FaceDetector.getFastDetector(Unknown Source:7)
        at com.onfido.android.sdk.capture.face.FaceDetector.close(Unknown Source:0)
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stopFaceTracking(Unknown Source:9)
        at com.onfido.android.sdk.capture.ui.camera.CapturePresenter.stop(Unknown Source:35)
        at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onStop(Unknown Source:8)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1433)
        at android.app.Activity.performStop(Activity.java:7489)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4196)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4174) 
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4249) 
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
        at android.content.IContentService$Stub.onTransact(IContentService.java:76)
        at com.android.server.content.ContentService.onTransact(ContentService.java:262)
        at android.os.Binder.execTransact(Binder.java:733)

**Comment by gokhanaliccii** [comment]
@527179023  Thanks for reporting the issue, I'll let you know when we resolved the issue.

**Comment by gokhanaliccii** [comment]
@527179023 Did you find chance to reproduce the crash ?

**Comment by 527179023** [comment]
Yes，We will also have a ZTE mobile phone reporting an error

**Comment by 527179023** [comment]
Hi~! Devices with no google service often crashed as above shows

**Comment by 527179023** [comment]
It has nothing to do with the model.  The device with no Google services will crash when using onfido sdk.

**Comment by arnas-savickis** [comment]
We are getting this kind of exception for huawei JNY-LX1, MED-LX9N devices. Any ideas how to address this issue?

**Comment by shaubert** [comment]
+1

**Comment by kondratk** [comment]
+1

**Comment by zhaolong6017** [comment]
I also encountered this problem. The specific solution is to customize a contentProvider and inherit from contentProvider. Then register this custom contentProvider in your AndroidManifest.xml file, define authorities as: com.google.android.gms.phenotype, and finally run it to solve the problem successfully.
AndroidManifest.xml code:
<provider
          android:name="com.legendwd.hyperpay.receiver.OnfdoProvider"
            android:authorities="com.google.android.gms.phenotype"
            android:exported="false" />

Custom contentProvider code:
public class OnfdoProvider extends ContentProvider {
    @Override
    public boolean onCreate() {
        return false;
    }

    @Nullable
    @Override
    public Cursor query(@NonNull Uri uri, @Nullable String[] projection, @Nullable String selection, @Nullable String[] selectionArgs, @Nullable String sortOrder) {
        return null;
    }

    @Nullable
    @Override
    public String getType(@NonNull Uri uri) {
        return null;
    }

    @Nullable
    @Override
    public Uri insert(@NonNull Uri uri, @Nullable ContentValues ​​values) {
        return null;
    }

    @Override
    public int delete(@NonNull Uri uri, @Nullable String selection, @Nullable String[] selectionArgs) {
        return 0;
    }

    @Override
    public int update(@NonNull Uri uri, @Nullable ContentValues ​​values, @Nullable String selection, @Nullable String[] selectionArgs) {
        return 0;
    }
}

**Comment by zhaolong6017** [comment]
AndroidManifest.xml code:
<provider
          android:name="com.legendwd.hyperpay.receiver.OnfdoProvider"
            android:authorities="com.google.android.gms.phenotype"
            android:exported="false" />

**Comment by zhaolong6017** [comment]
![image](https://user-images.githubusercontent.com/15864493/91529631-3681b080-e93c-11ea-8b3c-8f5ada2e8461.png)

**Comment by jlmcdonnell** [comment]
Is this being looked into? This is preventing users from uploading documents on the following devices:
- Huawei P20 Pro
- Huawei P40 Lite
- Xiaomi Redmi Note 7

They are all running Android 10.
Onfido SDK version: 5.0.1

**Comment by burakeregar** [comment]
We are currently investigating our compatibility with the devices without Google Play Servies. Onfido SDK has a dependency on Firebase ML Vision which requires Google Play Services to download ML models into the device which allows us to keep our SDK size small. There is also another library called `com.google.mlkit:face-detection` which bundles the ML model into the device, therefore, Firebase doesn't require Google Play Services anymore. However, that increases the app size by 16 MBs. (https://developers.google.com/ml-kit/vision/face-detection/android for more info).

We have tried this approach on our end with a Huawei P40 device and we managed to complete the flow without any issues. If you are able to reproduce the issue on your side, do you mind verifying this solution on your end?

```
implementation ("com.onfido.sdk.capture:onfido-capture-sdk:x.y.z"){
    exclude group: 'com.google.android.gms'
}

implementation 'com.google.mlkit:face-detection:16.0.2'
```

If this works, it is worth providing this build only to AppGallery to avoid introducing 16 MB difference to all users.

**Comment by LoverFancy** [comment]
> I also encountered this problem. The specific solution is to customize a contentProvider and inherit from contentProvider. Then register this custom contentProvider in your AndroidManifest.xml file, define authorities as: com.google.android.gms.phenotype, and finally run it to solve the problem successfully.
> AndroidManifest.xml code:
> Custom contentProvider code:
> public class OnfdoProvider extends ContentProvider {
> @override
> public boolean onCreate() {
> return false;
> }
> 
> ```
> @Nullable
> @Override
> public Cursor query(@NonNull Uri uri, @Nullable String[] projection, @Nullable String selection, @Nullable String[] selectionArgs, @Nullable String sortOrder) {
>     return null;
> }
> 
> @Nullable
> @Override
> public String getType(@NonNull Uri uri) {
>     return null;
> }
> 
> @Nullable
> @Override
> public Uri insert(@NonNull Uri uri, @Nullable ContentValues ​​values) {
>     return null;
> }
> 
> @Override
> public int delete(@NonNull Uri uri, @Nullable String selection, @Nullable String[] selectionArgs) {
>     return 0;
> }
> 
> @Override
> public int update(@NonNull Uri uri, @Nullable ContentValues ​​values, @Nullable String selection, @Nullable String[] selectionArgs) {
>     return 0;
> }
> ```
> 
> }





@zhaolong6017 @gokhanaliccii @burakeregar

I according to your method and solved the problem, but when I need to install another app on the same devices(such as install the test-app and install the production-app) found the below issue when I install secord app.

adb: failed to install Desktop/apk/release/app-release.apk: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name com.google.android.gms.phenotype (in package com.xxx.xxx.xxxx) is already used by com.xxx.xxx.xxxxdev]

The reason is used the same authorities in AndroidManifest.xml

```
      <provider
        android:name="com.rn_msdj.OnfdoProvider"
        android:authorities="com.google.android.gms.phenotype"
        android:exported="false">
      </provider>
```



could you help to give me some ideas. Thanks!

**Comment by TonyTwist** [comment]
> I also encountered this problem. The specific solution is to customize a contentProvider and inherit from contentProvider. Then register this custom contentProvider in your AndroidManifest.xml file, define authorities as: com.google.android.gms.phenotype, and finally run it to solve the problem successfully.
> AndroidManifest.xml code:
> Custom contentProvider code:
> public class OnfdoProvider extends ContentProvider {
> @override
> public boolean onCreate() {
> return false;
> }
> 
> ```
> @Nullable
> @Override
> public Cursor query(@NonNull Uri uri, @Nullable String[] projection, @Nullable String selection, @Nullable String[] selectionArgs, @Nullable String sortOrder) {
>     return null;
> }
> 
> @Nullable
> @Override
> public String getType(@NonNull Uri uri) {
>     return null;
> }
> 
> @Nullable
> @Override
> public Uri insert(@NonNull Uri uri, @Nullable ContentValues ​​values) {
>     return null;
> }
> 
> @Override
> public int delete(@NonNull Uri uri, @Nullable String selection, @Nullable String[] selectionArgs) {
>     return 0;
> }
> 
> @Override
> public int update(@NonNull Uri uri, @Nullable ContentValues ​​values, @Nullable String selection, @Nullable String[] selectionArgs) {
>     return 0;
> }
> ```
> 
> }

A good workaround!

**Comment by nic-bell** [comment]
> implementation ("com.onfido.sdk.capture:onfido-capture-sdk:x.y.z"){
>     exclude group: 'com.google.android.gms'
> }
> 
> implementation 'com.google.mlkit:face-detection:16.0.2'

@burakeregar we've tried this but still get crashes, possibly because the GMS libraries are dependencies of other libraries too which we have less control over. Is it possible to make Onfido only try load the models if they are actually missing? 
If we have `implementation 'com.google.mlkit:face-detection:16.0.2'` then it shouldn't attempt to download the models.

**Comment by kimrtaylor** [comment]
> implementation ("com.onfido.sdk.capture:onfido-capture-sdk:x.y.z"){
>     exclude group: 'com.google.android.gms'
> }
> 
> implementation 'com.google.mlkit:face-detection:16.0.2'

@burakeregar  We've also tried this solution and it did solve the issue when running on some emulators. However our users are still experiencing the crash on the following Huawei devices. Any update on this would be appreciated!

<img width="142" alt="Screenshot 2021-01-28 at 12 51 19" src="https://user-images.githubusercontent.com/3648218/106141149-a1434c00-6167-11eb-8303-73031c3dbd5e.png">
