### ISSUE TITLE
Error inflating class ImageView

### ISSUE THREAD

**Issue by iismagilov** [onfido/onfido-android-sdk#93]
#### What happened instead?
Fatal Exception: android.view.InflateException: Binary XML file line #68: Binary XML file line #68: Error inflating class ImageView
       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.onfido.android.sdk.capture.ui.BulletedMessageFragment.onCreateView(BulletedMessageFragment.java)
       at com.onfido.android.sdk.capture.ui.FaceIntroFragment.onCreateView(FaceIntroFragment.java)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5885)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
#### Version info:

- `onfido-capture-sdk` version: 5.2.0
- Android API version(s): Android 5/ Android 6

- `compileSdkVersion`:  29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable): androidx 1.0.0

#### Issue severity information (number of users/crashes if applicable):
250 users with ~1100 crashes

#### Other useful info:
_screenshots, videos, etc._

**Comment by Gorbyy** [comment]
Hi @iismagilov 

Your issue looks similar to this one: https://github.com/onfido/onfido-android-sdk/issues/86. We've provided a temporary solution in there - do you mind checking it and see if it works for you?

Thanks in advance

**Comment by iismagilov** [comment]
@Gorbyy Thanks for quick reply! Missed #86 my bad. We've decided to downgrade back to 5.0.2 version for now as it affects our users and we would like to deliver fix for them as quick as possible. So most probably we will wait for proper fix in the next release.

**Comment by bartzet** [comment]
Thanks @iismagilov

**Comment by bartzet** [comment]
Hello @iismagilov 

One more question, do you have more data on the devices this happened from your crash analytics? 

We'd appreciate if you could share it with us.

**Comment by iismagilov** [comment]
Hey @bartzet! I found extra logs which might be helpful for you (stacktrace is below). As well here is the top device models that were affected based on our analytic:
1. Samsung:
- Galaxy S5
- Galaxy A5
- Galaxy S5 mini
2. HUAWEI
- P8 Lite
- P8
3. Xiaomi
- Redmi 4 Pro
- Redmi Note 3
- Redmi Note 4

All devices are running on Android 5 and 6

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.core.content.res.ComplexColorCompat.isStateful()' on a null object reference
       at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VFullPath.isStateful(VectorDrawableCompat.java)
       at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VGroup.isStateful(VectorDrawableCompat.java)
       at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VPathRenderer.isStateful(VectorDrawableCompat.java)
       at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VectorDrawableCompatState.isStateful(VectorDrawableCompat.java)
       at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.isStateful(VectorDrawableCompat.java)
       at android.widget.ImageView.updateDrawable(ImageView.java:914)
       at android.widget.ImageView.setImageDrawable(ImageView.java:488)
       at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java)
       at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:195)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:758)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at com.onfido.android.sdk.capture.ui.BulletedMessageFragment.onCreateView(BulletedMessageFragment.java)
       at com.onfido.android.sdk.capture.ui.FaceIntroFragment.onCreateView(FaceIntroFragment.java)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by bartzet** [comment]
Thanks a lot 💯

**Comment by bartzet** [comment]
Hi again @iismagilov.

We are trying to fix this issue internally. Can you confirm that you meant you are going to downgrade to `5.0.1`. We have never released `5.0.2` version.

**Comment by iismagilov** [comment]
You are right, it's 5.0.1

**Comment by bartzet** [comment]
Hi @iismagilov.
We have released 5.3.1 version today fixing this issue. Please try and let us know if you experience any problems.
